# -*- coding: utf-8 -*-
"""Generate 03_empirical_statistics_and_covariance_fitting.ipynb"""
import nbformat as nbf

nb = nbf.v4.new_notebook()
nb.metadata['kernelspec'] = {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'}
nb.metadata['language_info'] = {'name': 'python', 'version': '3.9.0'}
cells = []

cells.append(nbf.v4.new_markdown_cell(
"# Tutorial 03 - Empirical Covariance Estimation & Model Fitting\n\n"
"**Package:** stamps_v3  \n"
"**MATLAB equivalent:** `STATLIBtutorial.m` §4-end  \n"
"**Dataset:** Falmagne soil dataset\n\n"
"---\n\n"
"## Learning objectives\n\n"
"1. Compute **empirical spatial covariance** with `stcov`.\n"
"2. Fit a nested covariance model by **Weighted Least Squares (WLS)** with `covmodelfit`.\n"
"3. Fit a **Linear Model of Coregionalisation (LMC)** for three variables "
"(sand, silt, clay) using `coregfit`.\n"
"4. Apply **Normal Score Transformation (NST)** with `other2gauss` and repeat "
"the covariance workflow on the transformed data.\n\n"
"### Key difference from MATLAB\n\n"
"> MATLAB's `vario()` computes the **variogram** $\\gamma(h) = \\frac{1}{2}\\text{E}[Z(\\mathbf{s}+\\mathbf{h})-Z(\\mathbf{s})]^2$.  \n"
"> stamps_v3's `stcov()` computes the **covariance** $C(h) = \\text{Cov}[Z(\\mathbf{s}), Z(\\mathbf{s}+\\mathbf{h})]$.  \n"
"> They are related by $C(h) = C(0) - \\gamma(h)$, but stamps uses covariances throughout.\n"
))

cells.append(nbf.v4.new_code_cell(
"import sys, os, pickle\n"
"import numpy as np\n"
"import pandas as pd\n"
"import matplotlib.pyplot as plt\n\n"
"REPO_ROOT = os.path.abspath(os.path.join(os.getcwd(), '..'))\n"
"if REPO_ROOT not in sys.path:\n"
"    sys.path.insert(0, REPO_ROOT)\n\n"
"from stamps.stamps.stats.dependence.stcov import stcov\n"
"from stamps.stamps.stats.dependence.stcovfit import covmodelfit, coregfit\n"
"from stamps.stamps.bme.bme_transform import other2gauss\n"
"from stamps.stamps.graph.modelplot import modelplot\n\n"
"plt.rcParams.update({'figure.dpi': 110, 'font.size': 10})\n"
"DATA_DIR = os.path.join(os.getcwd(), 'data')\n\n"
"with open(os.path.join(DATA_DIR, 'tutorial01_data.pkl'), 'rb') as f:\n"
"    d = pickle.load(f)\n"
"ch = d['ch']; sand = d['sand']; silt = d['silt']; clay = d['clay']\n"
"print('Loaded:', ch.shape, sand.shape)\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 1. Empirical spatial covariance with `stcov`\n\n"
"`stcov` computes the empirical covariance for each spatial lag class defined by "
"`lagS` (lag centres) and `lagS_range` (half-widths).\n\n"
"```python\n"
"lagCOVv, lagCOVn, lagSS, lagTT = stcov(\n"
"    grid_s, grid_t, grid_v,\n"
"    lagS, lagS_range,\n"
"    lagT=None, lagT_range=None   # omit for pure-spatial case\n"
")\n"
"```\n\n"
"**Return values:**\n"
"- `lagCOVv` — empirical covariance values\n"
"- `lagCOVn` — number of pairs per lag class\n"
"- `lagSS`, `lagTT` — spatial and temporal lag centres\n"
))

cells.append(nbf.v4.new_code_cell(
"# Spatial lag settings (in metres)\n"
"lagS       = np.arange(0, 13_500, 500.0)   # lag centres 0..13000 m\n"
"lagS_range = np.full(len(lagS), 500.0)      # half-width 500 m\n\n"
"# For pure-spatial stcov, wrap data as 2-D (grid_s=coords, grid_t=dummy, grid_v=data)\n"
"# stcov expects grid_s: (ns,d), grid_t: (nt,), grid_v: (ns, nt)\n"
"grid_s = ch                           # (118, 2)\n"
"grid_t = np.array([0.0])              # single time step\n"
"grid_v = sand[:, np.newaxis]          # (118, 1)\n\n"
"lagCOVv, lagCOVn, lagSS, lagTT = stcov(\n"
"    grid_s, grid_t, grid_v,\n"
"    lagS, lagS_range,\n"
")\n\n"
"# Extract the 1-D spatial covariance profile\n"
"lag_h = lagSS.ravel()     # spatial lag values\n"
"cov_h = lagCOVv.ravel()   # covariance at each lag\n"
"n_h   = lagCOVn.ravel()   # number of pairs\n\n"
"# Remove empty bins\n"
"valid = (n_h > 0) & ~np.isnan(cov_h)\n"
"lag_h, cov_h, n_h = lag_h[valid], cov_h[valid], n_h[valid]\n\n"
"print(f'Lag range  : {lag_h.min():.0f} - {lag_h.max():.0f} m')\n"
"print(f'C(0)       : {cov_h[0]:.4f}')\n"
"print(f'Lag bins used: {valid.sum()}')\n"
))

cells.append(nbf.v4.new_code_cell(
"fig, axes = plt.subplots(1, 2, figsize=(13, 4))\n\n"
"axes[0].plot(lag_h / 1000, cov_h, 'o', color='steelblue', ms=5, label='Empirical')\n"
"axes[0].axhline(0, color='gray', ls='--', lw=0.8)\n"
"axes[0].set_xlabel('Lag (km)'); axes[0].set_ylabel('Covariance')\n"
"axes[0].set_title('Empirical covariance - Sand')\n\n"
"# Equivalent variogram: gamma = C(0) - C(h)\n"
"gamma_h = cov_h[0] - cov_h\n"
"axes[1].plot(lag_h / 1000, gamma_h, 's', color='tomato', ms=5, label='Empirical')\n"
"axes[1].set_xlabel('Lag (km)'); axes[1].set_ylabel('gamma(h)')\n"
"axes[1].set_title('Equivalent variogram - Sand\\n(derived from covariance)')\n\n"
"for ax in axes:\n"
"    ax.legend(); ax.grid(True, alpha=0.3)\n"
"plt.tight_layout(); plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 2. Fitting a nested covariance model by WLS\n\n"
"`covmodelfit` minimises the weighted sum of squared residuals between the "
"empirical covariance values and the model prediction:\n\n"
r"$$\text{WSS} = \sum_k n_k \left[\hat{C}(h_k) - C_{\text{model}}(h_k)\right]^2$$"
"\n\nwhere $n_k$ is the number of pairs used to estimate $\\hat{C}(h_k)$.\n"
))

cells.append(nbf.v4.new_code_cell(
"# Nested model: nugget + spherical\n"
"# covparam0 = initial guesses: [sill0], [sill1, range1]\n"
"covmodel  = ['nuggetC', 'sphericalC']\n"
"covparam0 = [(20.0,), (80.0, 5_000.0)]\n\n"
"# covmodelfit expects:\n"
"#   covmodelfit(lag_cov_s, lag_cov_t, lag_cov_v, lag_cov_n, covmodel, covparam0)\n"
"lag_cov_s = lag_h.reshape(-1, 1)    # (n_valid, 1) spatial lags\n"
"lag_cov_t = np.array([[0.0]])        # (1, 1) dummy time lag\n"
"lag_cov_v = cov_h.reshape(-1, 1)    # (n_valid, 1) empirical covariances\n"
"lag_cov_n = n_h.reshape(-1, 1)      # (n_valid, 1) pair counts\n\n"
"result = covmodelfit(lag_cov_s, lag_cov_t, lag_cov_v, lag_cov_n,\n"
"                     covmodel, covparam0)\n"
"fitted_covparam = result['covparam']\n"
"print('Fitted parameters:')\n"
"for m, p in zip(covmodel, fitted_covparam):\n"
"    print(f'  {m}: {np.array(p).round(2)}')\n"
))

cells.append(nbf.v4.new_code_cell(
"from stamps.stamps.models.covmodel import nuggetC, sphericalC\n\n"
"h_plot = np.linspace(0, lag_h.max(), 300)\n"
"C_fitted = (nuggetC(h_plot, *fitted_covparam[0])\n"
"           + sphericalC(h_plot, *fitted_covparam[1]))\n\n"
"fig, axes = plt.subplots(1, 2, figsize=(13, 4))\n\n"
"axes[0].plot(lag_h / 1000, cov_h,   'o', color='steelblue', ms=5, label='Empirical')\n"
"axes[0].plot(h_plot / 1000, C_fitted, '-', color='tomato',   lw=2,  label='Fitted model')\n"
"axes[0].set_xlabel('Lag (km)'); axes[0].set_ylabel('Covariance')\n"
"axes[0].set_title('Sand covariance: empirical vs fitted'); axes[0].legend()\n\n"
"gamma_fitted = C_fitted[0] - C_fitted\n"
"gamma_data   = cov_h[0] - cov_h\n"
"axes[1].plot(lag_h / 1000, gamma_data,   's', color='tomato',   ms=5, label='Empirical')\n"
"axes[1].plot(h_plot / 1000, gamma_fitted, '-', color='steelblue', lw=2,  label='Fitted model')\n"
"axes[1].set_xlabel('Lag (km)'); axes[1].set_ylabel('gamma(h)')\n"
"axes[1].set_title('Equivalent variogram: empirical vs fitted'); axes[1].legend()\n\n"
"for ax in axes: ax.grid(True, alpha=0.3)\n"
"plt.tight_layout(); plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 3. Empirical covariance for silt and clay\n"
))

cells.append(nbf.v4.new_code_cell(
"def compute_stcov_1d(ch, z, lagS, lagS_range):\n"
"    '''Helper: compute 1-D empirical covariance for a single variable.'''\n"
"    grid_v = z[:, np.newaxis]\n"
"    grid_t = np.array([0.0])\n"
"    lagCOVv, lagCOVn, lagSS, _ = stcov(ch, grid_t, grid_v, lagS, lagS_range)\n"
"    h   = lagSS.ravel()\n"
"    C   = lagCOVv.ravel()\n"
"    n   = lagCOVn.ravel()\n"
"    ok  = (n > 0) & ~np.isnan(C)\n"
"    return h[ok], C[ok], n[ok]\n\n\n"
"lag_s_silt, cov_silt, n_silt = compute_stcov_1d(ch, silt, lagS, lagS_range)\n"
"lag_s_clay, cov_clay, n_clay = compute_stcov_1d(ch, clay, lagS, lagS_range)\n\n"
"fig, axes = plt.subplots(1, 3, figsize=(17, 4))\n"
"data_list = [('Sand', lag_h,     cov_h,     'steelblue'),\n"
"             ('Silt', lag_s_silt, cov_silt, 'goldenrod'),\n"
"             ('Clay', lag_s_clay, cov_clay, 'tomato')]\n\n"
"for ax, (name, lh, ch_cov, col) in zip(axes, data_list):\n"
"    ax.plot(lh / 1000, ch_cov, 'o', color=col, ms=5)\n"
"    ax.axhline(0, color='gray', ls='--', lw=0.8)\n"
"    ax.set_xlabel('Lag (km)'); ax.set_ylabel('Covariance')\n"
"    ax.set_title(f'{name} - empirical covariance'); ax.grid(True, alpha=0.3)\n\n"
"plt.tight_layout(); plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 4. Linear Model of Coregionalisation (LMC) with `coregfit`\n\n"
"When working with multiple co-located variables, we need a **jointly valid** "
"cross-covariance model.  The LMC assumes:\n\n"
r"$$C_{ij}(h) = \sum_{u=1}^{U} b^{(u)}_{ij}\, g_u(h)$$"
"\n\nwhere $g_u(h)$ are basic covariance models and "
r"$\mathbf{B}^{(u)} = [b^{(u)}_{ij}]$ are positive semi-definite **coregionalisation matrices**."
"\n\n"
"`coregfit` uses Iterated Alternating Weighted Least Squares (IALS) to estimate "
"the $\\mathbf{B}^{(u)}$ matrices jointly.\n"
))

cells.append(nbf.v4.new_code_cell(
"# Build a 3-variable empirical cross-covariance structure\n"
"# d[k,l] = lag, V[k,l] = covariance of variable pair (k,l)\n"
"# We stack the three variables and compute pairwise covariances\n\n"
"variables_all  = np.column_stack([sand, silt, clay])  # (118, 3)\n"
"nv = 3\n\n"
"# Compute empirical covariance for all 6 unique pairs (including auto-covariances)\n"
"pair_names = ['Sand-Sand', 'Silt-Silt', 'Clay-Clay',\n"
"              'Sand-Silt', 'Sand-Clay', 'Silt-Clay']\n"
"pair_idx   = [(0,0), (1,1), (2,2), (0,1), (0,2), (1,2)]\n\n"
"cov_data = {}\n"
"for (i, j), name in zip(pair_idx, pair_names):\n"
"    # Cross-covariance: compute product of mean-centred values\n"
"    zi = variables_all[:, i] - variables_all[:, i].mean()\n"
"    zj = variables_all[:, j] - variables_all[:, j].mean()\n"
"    # Use stcov on the pairwise product as a proxy\n"
"    prod_ij = (zi * zj)[:, np.newaxis]\n"
"    lh, _, n = compute_stcov_1d(ch, (variables_all[:, i] + variables_all[:, j]) / 2,\n"
"                                 lagS, lagS_range)\n"
"    # Proper cross-covariance via manual lag binning\n"
"    lh_i, cv_i, _ = compute_stcov_1d(ch, variables_all[:, i], lagS, lagS_range)\n"
"    lh_j, cv_j, _ = compute_stcov_1d(ch, variables_all[:, j], lagS, lagS_range)\n"
"    # For same lag bins, approximate cross-cov from individual stcov calls\n"
"    # (true cross-cov needs the paired product; use correlation-weighted estimate)\n"
"    cov_data[name] = (lh_i, cv_i)\n\n"
"# For coregfit we build stacked D and V matrices across lags\n"
"# D: (n_lags,) lag values shared, V: (nv, nv, n_lags) cross-covariance tensor\n"
"# Here we use the auto-covariances on the diagonal and 0 off-diagonal (simplification)\n"
"n_lags = len(lag_h)\n"
"D_arr  = lag_h                                      # shared lag axis\n\n"
"# Build cross-covariance matrix at each lag\n"
"# For a proper implementation, compute pairwise cross-covariances\n"
"# using the 'difference' method or moment estimator\n"
"V_tensor = np.zeros((nv, nv, n_lags))\n"
"for vi, var in enumerate([sand, silt, clay]):\n"
"    lh_vi, cv_vi, _ = compute_stcov_1d(ch, var, lagS, lagS_range)\n"
"    n_common = min(n_lags, len(cv_vi))\n"
"    V_tensor[vi, vi, :n_common] = cv_vi[:n_common]\n\n"
"# Compute cross-covariances using the linear combination trick:\n"
"# C_XY = 0.5*(C_(X+Y) - C_X - C_Y)\n"
"pairs_xy = [(0,1,'sand_silt'), (0,2,'sand_clay'), (1,2,'silt_clay')]\n"
"var_arrays = [sand, silt, clay]\n"
"for (i, j, _) in pairs_xy:\n"
"    zi = var_arrays[i]; zj = var_arrays[j]\n"
"    _, cv_sum, _ = compute_stcov_1d(ch, zi + zj, lagS, lagS_range)\n"
"    _, cv_i,   _ = compute_stcov_1d(ch, zi,       lagS, lagS_range)\n"
"    _, cv_j,   _ = compute_stcov_1d(ch, zj,       lagS, lagS_range)\n"
"    n_c = min(n_lags, len(cv_sum), len(cv_i), len(cv_j))\n"
"    V_tensor[i, j, :n_c] = 0.5 * (cv_sum[:n_c] - cv_i[:n_c] - cv_j[:n_c])\n"
"    V_tensor[j, i, :n_c] = V_tensor[i, j, :n_c]  # symmetry\n\n"
"print('Cross-covariance tensor shape:', V_tensor.shape)\n"
"print('C(0) matrix (variance-covariance at lag 0):')\n"
"print(np.round(V_tensor[:, :, 0], 2))\n"
))

cells.append(nbf.v4.new_code_cell(
"# Fit LMC: nugget + spherical structure\n"
"lmc_model  = ['nuggetC', 'sphericalC']\n"
"lmc_param0 = [(10.0,), (50.0, 5_000.0)]\n\n"
"# coregfit(d, V, o, model, param0)\n"
"# d: (n_lags,) lag values\n"
"# V: (nv, nv, n_lags) cross-covariance tensor\n"
"# o: (n_lags,) weights (use pair counts, approximate here)\n"
"o_weights = n_h.copy()   # use sand pair counts as weights\n\n"
"lmc_result = coregfit(D_arr, V_tensor, o_weights, lmc_model, lmc_param0)\n\n"
"print('LMC fitting result:')\n"
"for s in lmc_result:\n"
"    print(f'  Structure: {s[\"model\"]}')\n"
"    print(f'    Sill matrix (B):\\n{np.round(s[\"sill_matrix\"], 2)}')\n"
"    if 'range_param' in s:\n"
"        print(f'    Range: {s[\"range_param\"]:.1f} m')\n"
))

cells.append(nbf.v4.new_code_cell(
"# Visualise fitted LMC: diagonal auto-covariances\n"
"from stamps.stamps.models.covmodel import nuggetC, sphericalC\n\n"
"h_plot = np.linspace(0, D_arr.max(), 300)\n\n"
"fig, axes = plt.subplots(1, 3, figsize=(16, 4))\n"
"varnames = ['Sand', 'Silt', 'Clay']\n"
"colors_v = ['steelblue', 'goldenrod', 'tomato']\n\n"
"for vi, (ax, vname, col) in enumerate(zip(axes, varnames, colors_v)):\n"
"    # Empirical\n"
"    _, cv_vi, _ = compute_stcov_1d(ch, var_arrays[vi], lagS, lagS_range)\n"
"    lh_vi = lag_h[:len(cv_vi)]\n"
"    ax.plot(lh_vi / 1000, cv_vi, 'o', color=col, ms=5, label='Empirical')\n\n"
"    # Fitted LMC diagonal\n"
"    C_fit = np.zeros(len(h_plot))\n"
"    for s in lmc_result:\n"
"        fn   = nuggetC if s['model'] == 'nuggetC' else sphericalC\n"
"        b_ii = s['sill_matrix'][vi, vi]\n"
"        rp   = s.get('range_param', None)\n"
"        if rp is None:\n"
"            C_fit += fn(h_plot, b_ii)\n"
"        else:\n"
"            C_fit += fn(h_plot, b_ii, rp)\n\n"
"    ax.plot(h_plot / 1000, C_fit, '-', color='k', lw=2, label='LMC fit')\n"
"    ax.set_xlabel('Lag (km)'); ax.set_ylabel('Covariance')\n"
"    ax.set_title(f'{vname}: empirical vs LMC'); ax.legend(); ax.grid(True, alpha=0.3)\n\n"
"plt.suptitle('LMC diagonal auto-covariances', fontsize=12, y=1.01)\n"
"plt.tight_layout(); plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 5. Normal Score Transformation (NST)\n\n"
"Many geostatistical methods (especially BME) assume **Gaussian marginals**.  "
"The Normal Score Transformation maps the original data $z$ to a Gaussian "
"variable $y$ via the empirical CDF:\n\n"
r"$$y_i = \Phi^{-1}\!\left[\hat{F}(z_i)\right]$$"
"\n\n"
"After transformation, we can fit a covariance model in Gaussian space and "
"back-transform the results.\n\n"
"`stamps.bme.bme_transform.other2gauss` implements this using a reference CDF "
"(either empirical or user-supplied).\n"
))

cells.append(nbf.v4.new_code_cell(
"# Normal Score Transform for sand\n"
"# other2gauss(z, yfile, cdfyfile)\n"
"# yfile    : reference y values (Gaussian quantiles)\n"
"# cdfyfile : corresponding CDF values\n\n"
"# Build empirical CDF for sand\n"
"z_sorted = np.sort(sand)\n"
"n        = len(z_sorted)\n"
"p_vals   = (np.arange(1, n + 1) - 0.5) / n    # Hazen plotting position\n\n"
"from scipy.stats import norm\n"
"y_gauss = norm.ppf(p_vals)                      # Gaussian quantiles\n\n"
"# Apply NST via other2gauss\n"
"sand_nst = other2gauss(sand, z_sorted, p_vals)\n\n"
"print(f'Original sand: mean={sand.mean():.2f}, std={sand.std():.2f}')\n"
"print(f'NST sand:      mean={sand_nst.mean():.4f}, std={sand_nst.std():.4f}')\n"
))

cells.append(nbf.v4.new_code_cell(
"fig, axes = plt.subplots(1, 3, figsize=(16, 4))\n\n"
"# Histogram comparison\n"
"ax = axes[0]\n"
"ax.hist(sand,     bins=20, density=True, color='steelblue', alpha=0.6, label='Original')\n"
"ax.hist(sand_nst, bins=20, density=True, color='tomato',    alpha=0.6, label='NST')\n"
"h_ax = np.linspace(-3.5, 3.5, 200)\n"
"ax.plot(h_ax, norm.pdf(h_ax), 'k-', lw=2, label='N(0,1)')\n"
"ax.set_xlabel('Value'); ax.set_ylabel('Density')\n"
"ax.set_title('Sand: before vs after NST'); ax.legend()\n\n"
"# Scatter: original vs transformed\n"
"ax = axes[1]\n"
"ax.scatter(sand, sand_nst, s=15, alpha=0.6, color='steelblue')\n"
"ax.set_xlabel('Original sand (%)'); ax.set_ylabel('NST sand (std. units)')\n"
"ax.set_title('NST transformation curve'); ax.grid(True, alpha=0.3)\n\n"
"# Empirical covariance in transformed space\n"
"lh_nst, cov_nst, n_nst = compute_stcov_1d(ch, sand_nst, lagS, lagS_range)\n"
"ax = axes[2]\n"
"ax.plot(lag_h / 1000,  cov_h,   'o', color='steelblue', ms=5, label='Original sand')\n"
"ax.plot(lh_nst / 1000, cov_nst, 's', color='tomato',    ms=5, label='NST sand')\n"
"ax.axhline(0, color='gray', ls='--', lw=0.8)\n"
"ax.set_xlabel('Lag (km)'); ax.set_ylabel('Covariance')\n"
"ax.set_title('Covariance: original vs NST sand'); ax.legend()\n\n"
"plt.tight_layout(); plt.show()\n"
))

cells.append(nbf.v4.new_code_cell(
"# Fit covariance model to NST-transformed data\n"
"lag_cov_v_nst = cov_nst.reshape(-1, 1)\n"
"lag_cov_n_nst = n_nst.reshape(-1, 1)\n"
"lag_cov_s_nst = lh_nst.reshape(-1, 1)\n\n"
"result_nst = covmodelfit(lag_cov_s_nst, np.array([[0.0]]),\n"
"                         lag_cov_v_nst, lag_cov_n_nst,\n"
"                         ['nuggetC', 'sphericalC'],\n"
"                         [(0.05,), (0.95, 5_000.0)])\n"
"fitted_nst = result_nst['covparam']\n"
"print('NST model parameters:')\n"
"for m, p in zip(['nuggetC', 'sphericalC'], fitted_nst):\n"
"    print(f'  {m}: {np.array(p).round(4)}')\n\n"
"h_plot = np.linspace(0, lh_nst.max(), 300)\n"
"C_nst_fitted = (nuggetC(h_plot, *fitted_nst[0])\n"
"               + sphericalC(h_plot, *fitted_nst[1]))\n\n"
"fig, ax = plt.subplots(figsize=(7, 4))\n"
"ax.plot(lh_nst / 1000, cov_nst,     'o', color='tomato', ms=5, label='NST empirical')\n"
"ax.plot(h_plot / 1000, C_nst_fitted, '-', color='k',     lw=2,  label='NST fitted')\n"
"ax.set_xlabel('Lag (km)'); ax.set_ylabel('Covariance')\n"
"ax.set_title('NST sand: empirical covariance + fitted model'); ax.legend()\n"
"ax.grid(True, alpha=0.3); plt.tight_layout(); plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 6. Save covariance parameters for downstream notebooks\n"
))

cells.append(nbf.v4.new_code_cell(
"import pickle\n\n"
"cov_params = {\n"
"    # Univariate (sand) in original space\n"
"    'sand_covmodel':  ['nuggetC', 'sphericalC'],\n"
"    'sand_covparam':  fitted_covparam,\n"
"    # Univariate (sand) in NST space\n"
"    'sand_nst_covmodel': ['nuggetC', 'sphericalC'],\n"
"    'sand_nst_covparam': fitted_nst,\n"
"    # NST CDF (for back-transformation)\n"
"    'sand_z_sorted': z_sorted,\n"
"    'sand_p_vals':   p_vals,\n"
"    # LMC result\n"
"    'lmc_model':  lmc_model,\n"
"    'lmc_result': lmc_result,\n"
"    # Empirical lag data\n"
"    'lag_h': lag_h, 'cov_h': cov_h, 'n_h': n_h,\n"
"}\n\n"
"save_path = os.path.join(DATA_DIR, 'tutorial03_cov.pkl')\n"
"with open(save_path, 'wb') as f:\n"
"    pickle.dump(cov_params, f)\n"
"print('Saved:', save_path)\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 7. Summary\n\n"
"| Step | stamps_v3 function |\n"
"|---|---|\n"
"| Empirical covariance | `stcov(grid_s, grid_t, grid_v, lagS, lagS_range)` |\n"
"| WLS model fitting | `covmodelfit(lag_s, lag_t, lag_v, lag_n, model, param0)` |\n"
"| LMC cross-covariance fitting | `coregfit(d, V, o, model, param0)` |\n"
"| Normal Score Transformation | `other2gauss(z, z_sorted, p_vals)` |\n\n"
"**Next:** Tutorial 04 — Kriging, Cokriging & Kriging with Transformation.\n"
))

nb.cells = cells
import nbformat
with open("tutorials/03_empirical_statistics_and_covariance_fitting.ipynb", "w") as f:
    nbformat.write(nb, f)
print("Written: tutorials/03_empirical_statistics_and_covariance_fitting.ipynb")
