# -*- coding: utf-8 -*-
"""Generate 06_bme_probabilistic_soft_data.ipynb"""
import nbformat as nbf

nb = nbf.v4.new_notebook()
nb.metadata['kernelspec'] = {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'}
nb.metadata['language_info'] = {'name': 'python', 'version': '3.9.0'}
cells = []

cells.append(nbf.v4.new_markdown_cell(
"# Tutorial 06 - BME with Full Probabilistic Soft Data\n\n"
"**Package:** stamps_v3  \n"
"**MATLAB equivalent:** `BMEPROBALIBtutorial.m` (Part 1 - 2D spatial)\n"
"**Dataset:** Synthetic dataset generated from the Falmagne covariance model\n\n"
"---\n\n"
"## Learning objectives\n\n"
"1. Generate a **synthetic spatial dataset** using Cholesky simulation (`simuchol`).\n"
"2. Encode data as **Gaussian soft PDFs** and **uniform interval PDFs** using "
"   `probaGaussian` and `probaUniform`.\n"
"3. Run **BME posterior moments** over a spatial grid using `BMEPosteriorMoments`.\n"
"4. Compute the **full posterior PDF** at selected locations using `BMEPosteriorPDF`.\n"
"5. Compute **credible intervals** (68%, 90%, 99%) using `BMEPosteriorCI`.\n\n"
"### Probabilistic vs. interval soft data\n\n"
"- **Interval (Tutorial 05)**: uniform PDF over $[z^{lo}, z^{up}]$.\n"
"- **Probabilistic (this tutorial)**: any non-negative function $f(z) \\ge 0$ "
"  with $\\int f(z)\\,dz = 1$.  This is the most general BME soft data type.\n"
))

cells.append(nbf.v4.new_code_cell(
"import sys, os, pickle\n"
"import numpy as np\n"
"import matplotlib.pyplot as plt\n\n"
"REPO_ROOT = os.path.abspath(os.path.join(os.getcwd(), '..'))\n"
"if REPO_ROOT not in sys.path:\n"
"    sys.path.insert(0, REPO_ROOT)\n\n"
"from stamps.stats.simulation.simulation import simuchol\n"
"from stamps.bme.softconverter import probaGaussian, probaUniform, proba2stat\n"
"from stamps.bme.BMEprobaEstimations import (\n"
"    BMEPosteriorMoments,\n"
"    BMEPosteriorPDF,\n"
"    BMEPosteriorCI,\n"
")\n\n"
"plt.rcParams.update({'figure.dpi': 110, 'font.size': 10})\n"
"DATA_DIR = os.path.join(os.getcwd(), 'data')\n\n"
"# Load covariance model from Tutorial 03\n"
"with open(os.path.join(DATA_DIR, 'tutorial03_cov.pkl'), 'rb') as f:\n"
"    cov = pickle.load(f)\n"
"covmodel = cov['sand_covmodel']\n"
"covparam = cov['sand_covparam']\n\n"
"print('Covariance model:', covmodel)\n"
"for m, p in zip(covmodel, covparam):\n"
"    print(f'  {m}: {np.round(p, 2)}')\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 1. Generate a synthetic spatial dataset\n\n"
"We create a controlled experiment on a 15 x 15 grid by simulating from the "
"known covariance model.  This allows us to verify our BME estimates against "
"the known truth.\n"
))

cells.append(nbf.v4.new_code_cell(
"# Create a 15x15 regular grid\n"
"rng = np.random.default_rng(seed=42)\n"
"nx, ny = 15, 15\n"
"x_sim = np.linspace(0, 28_000, nx)\n"
"y_sim = np.linspace(0, 20_000, ny)\n"
"XX, YY = np.meshgrid(x_sim, y_sim)\n"
"grid_coords = np.column_stack([XX.ravel(), YY.ravel()])\n\n"
"# Simulate one realisation from the covariance model (zero-mean Gaussian)\n"
"zh_sim, _ = simuchol(grid_coords, covmodel, covparam, ns=1, seed=42)\n"
"zh_full   = zh_sim[:, 0]   # (n_grid,) true field\n\n"
"print(f'Simulated field shape: {zh_full.shape}')\n"
"print(f'True mean : {zh_full.mean():.3f}  (expected 0 for zero-mean)')\n"
"print(f'True var  : {zh_full.var():.3f}')\n\n"
"fig, ax = plt.subplots(figsize=(8, 6))\n"
"sc = ax.scatter(grid_coords[:, 0], grid_coords[:, 1], c=zh_full,\n"
"                cmap='RdYlBu_r', s=80, edgecolors='k', lw=0.3)\n"
"plt.colorbar(sc, ax=ax, label='Simulated Z')\n"
"ax.set_title('True simulated field (for verification)')\n"
"ax.set_aspect('equal')\n"
"ax.set_xlabel('X (m)')\n"
"ax.set_ylabel('Y (m)')\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 2. Create hard data and soft data subsets\n\n"
"From the simulated field we extract:\n\n"
"- **Hard data** (exact values): 40 locations randomly selected.\n"
"- **Gaussian soft data**: 30 locations with noisy measurements "
"  (mean = true value, std = 2 units).\n"
"- **Estimation grid**: the remaining locations.\n"
))

cells.append(nbf.v4.new_code_cell(
"n_grid = len(grid_coords)\n"
"idx_all = rng.permutation(n_grid)\n\n"
"n_hard = 40\n"
"n_soft = 30\n\n"
"idx_hard = idx_all[:n_hard]\n"
"idx_soft = idx_all[n_hard:n_hard + n_soft]\n"
"idx_est  = idx_all[n_hard + n_soft:]\n\n"
"# Hard data\n"
"ch_syn = grid_coords[idx_hard]      # (n_hard, 2)\n"
"zh_syn = zh_full[idx_hard]          # (n_hard,) exact values\n\n"
"# Gaussian soft data: noisy measurements\n"
"noise_std = 2.0\n"
"cs_syn    = grid_coords[idx_soft]   # (n_soft, 2)\n"
"z_soft_mean = zh_full[idx_soft] + rng.normal(0, noise_std, n_soft)  # noisy mean\n"
"z_soft_std  = noise_std * np.ones(n_soft)                            # known uncertainty\n\n"
"# Estimation grid (remaining locations)\n"
"ck_syn  = grid_coords[idx_est]      # estimation coords\n"
"z_true  = zh_full[idx_est]          # true values for verification\n\n"
"print(f'Hard data     : {n_hard} locations')\n"
"print(f'Gaussian soft : {n_soft} locations  (noise std={noise_std})')\n"
"print(f'Estimation    : {len(ck_syn)} locations')\n\n"
"fig, ax = plt.subplots(figsize=(8, 6))\n"
"ax.scatter(ck_syn[:, 0],  ck_syn[:, 1],  c='lightgrey', s=25, alpha=0.6, label='Estimation')\n"
"ax.scatter(cs_syn[:, 0],  cs_syn[:, 1],  c='steelblue', s=60, marker='o',\n"
"           edgecolors='navy', lw=0.5, label=f'Gaussian soft (n={n_soft})')\n"
"ax.scatter(ch_syn[:, 0],  ch_syn[:, 1],  c='tomato',    s=80, marker='s',\n"
"           edgecolors='k',    lw=0.5, label=f'Hard data (n={n_hard})')\n"
"ax.set_title('Data configuration')\n"
"ax.set_aspect('equal')\n"
"ax.set_xlabel('X (m)')\n"
"ax.set_ylabel('Y (m)')\n"
"ax.legend()\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 3. Encode Gaussian soft PDFs with `probaGaussian`\n\n"
"`probaGaussian` discretises a Gaussian distribution at each soft data location "
"into the stamps piecewise-linear PDF format:\n\n"
"```python\n"
"zs = probaGaussian(zmean, zstd)\n"
"# Returns: [softpdftype, nl, limi, probdens]\n"
"```\n\n"
"The resulting PDFs are centred on the noisy measurement with spread proportional "
"to the measurement error.\n"
))

cells.append(nbf.v4.new_code_cell(
"# Check probaGaussian signature\n"
"import inspect\n"
"print(inspect.signature(probaGaussian))\n"
))

cells.append(nbf.v4.new_code_cell(
"from stamps.bme.softconverter import probaGaussian\n\n"
"# Encode as Gaussian soft data\n"
"zs_gauss = probaGaussian(z_soft_mean, z_soft_std)\n"
"soft_type, nl_g, limi_g, pd_g = zs_gauss\n\n"
"print(f'softpdftype : {soft_type}')\n"
"print(f'nl shape    : {nl_g.shape}  (max nl = {nl_g.max()})')\n"
"print(f'limi shape  : {limi_g.shape}')\n"
"print(f'probdens shape: {pd_g.shape}')\n\n"
"# Compute soft data statistics\n"
"s_mean, s_var = proba2stat(soft_type, nl_g, limi_g, pd_g)\n"
"print(f'\\nMean of soft means : {s_mean.mean():.3f}')\n"
"print(f'Mean of soft vars  : {s_var.mean():.3f}  (expected ~{noise_std**2:.1f})')\n\n"
"# Visualise PDFs at a few locations\n"
"fig, axes = plt.subplots(1, 4, figsize=(16, 3))\n"
"for i, ax in enumerate(axes):\n"
"    n_i = int(nl_g[i, 0])\n"
"    x_i = limi_g[i, :n_i]\n"
"    y_i = pd_g[i, :n_i]\n"
"    ax.plot(x_i, y_i, 'steelblue', lw=2)\n"
"    ax.axvline(zh_full[idx_soft[i]], color='tomato', ls='--', lw=1.5, label='True')\n"
"    ax.axvline(z_soft_mean[i], color='steelblue', ls=':', lw=1.5, label='Meas')\n"
"    ax.set_title(f'Soft loc {i}')\n"
"    ax.set_xlabel('Z')\n"
"    if i == 0:\n"
"        ax.set_ylabel('f(z)')\n"
"        ax.legend(fontsize=8)\n"
"plt.suptitle('Gaussian soft PDFs at selected locations', y=1.01)\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 4. BME posterior moments\n\n"
"Combine hard and Gaussian-soft data to compute BME posterior mean and variance "
"at all estimation grid nodes.\n"
))

cells.append(nbf.v4.new_code_cell(
"nhmax = 10\n"
"nsmax = 8\n"
"dmax  = 12_000.0\n\n"
"print('Running BMEPosteriorMoments (synthetic dataset)...')\n"
"result_bme = BMEPosteriorMoments(\n"
"    ck_syn,\n"
"    ch=ch_syn, cs=cs_syn,\n"
"    zh=zh_syn.reshape(-1, 1),\n"
"    zs=tuple(zs_gauss),\n"
"    covmodel=covmodel, covparam=covparam,\n"
"    order=np.nan,\n"
"    nhmax=nhmax, nsmax=nsmax,\n"
"    dmax=np.array([[dmax]]),\n"
")\n"
"bme_mean = result_bme[:, 0]\n"
"bme_var  = result_bme[:, 1]\n\n"
"# Error vs truth\n"
"valid  = ~np.isnan(bme_mean)\n"
"rmse   = np.sqrt(np.mean((bme_mean[valid] - z_true[valid])**2))\n"
"print(f'BME RMSE vs truth : {rmse:.4f}')\n"
"print(f'Mean BME variance : {np.nanmean(bme_var):.4f}')\n"
))

cells.append(nbf.v4.new_code_cell(
"# Reconstruct full grid for display\n"
"z_display_mean = np.full(n_grid, np.nan)\n"
"z_display_var  = np.full(n_grid, np.nan)\n"
"z_display_true = np.full(n_grid, np.nan)\n"
"z_display_mean[idx_est] = bme_mean\n"
"z_display_var[idx_est]  = bme_var\n"
"z_display_true[idx_est] = z_true\n\n"
"Z_mean = z_display_mean.reshape(ny, nx)\n"
"Z_var  = z_display_var.reshape(ny, nx)\n"
"Z_true = z_display_true.reshape(ny, nx)\n\n"
"fig, axes = plt.subplots(1, 3, figsize=(17, 5))\n\n"
"def show_grid(ax, Z, title, vmin=None, vmax=None, cmap='RdYlBu_r', cbar_label=''):\n"
"    vm = vmin if vmin is not None else np.nanpercentile(Z, 2)\n"
"    vx = vmax if vmax is not None else np.nanpercentile(Z, 98)\n"
"    im = ax.pcolormesh(x_sim, y_sim, Z, cmap=cmap,\n"
"                       vmin=vm, vmax=vx, shading='nearest')\n"
"    plt.colorbar(im, ax=ax, label=cbar_label)\n"
"    ax.set_title(title); ax.set_aspect('equal')\n"
"    ax.set_xlabel('X (m)'); ax.set_ylabel('Y (m)')\n\n"
"vz_lo = np.nanpercentile(zh_full, 2)\n"
"vz_hi = np.nanpercentile(zh_full, 98)\n\n"
"show_grid(axes[0], Z_true, 'True values', vz_lo, vz_hi, cbar_label='Z')\n"
"show_grid(axes[1], Z_mean, 'BME mean estimate', vz_lo, vz_hi, cbar_label='Z')\n"
"show_grid(axes[2], Z_var,  'BME variance', cmap='Blues', cbar_label='Variance')\n\n"
"# Overlay hard and soft data\n"
"for ax in axes[:2]:\n"
"    ax.scatter(ch_syn[:, 0], ch_syn[:, 1], c='k', s=30, marker='s', zorder=4)\n"
"    ax.scatter(cs_syn[:, 0], cs_syn[:, 1], c='white', s=20,\n"
"               edgecolors='steelblue', lw=0.7, zorder=3)\n\n"
"plt.suptitle('BME estimation with Gaussian soft data', fontsize=12, y=1.01)\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 5. Posterior PDF at a single location\n\n"
"`BMEPosteriorPDF` computes the full posterior PDF $f_k(z)$ at each "
"estimation location.  The z evaluation range is determined automatically "
"from the data and model (Gaussian-approximated posterior moments), so no "
"z-grid needs to be supplied.  An explicit ``z_grid`` can be passed when a "
"fixed range is preferred.  This is the full Bayesian result — the posterior "
"moments computed above are derived from it.\n"
))

cells.append(nbf.v4.new_code_cell(
"# Choose a single estimation location near the centre\n"
"i_sel = len(ck_syn) // 2\n"
"ck_single = ck_syn[[i_sel], :]   # shape (1, 2)\n\n"
"# Z-grid for PDF evaluation\n"
"z_min = zh_full.min() - 2\n"
"z_max = zh_full.max() + 2\n"
"z_grid = np.linspace(z_min, z_max, 150)\n\n"
"print(f'Computing posterior PDF at location {ck_single[0]}...')\n"
"# BMEPosteriorPDF returns (z_out, pdf_values, info)\n"
"z_out, pdf_values, info_pdf = BMEPosteriorPDF(\n"
"    ck_single,\n"
"    ch=ch_syn, cs=cs_syn,\n"
"    zh=zh_syn.reshape(-1, 1),\n"
"    zs=zs_gauss,\n"
"    covmodel=covmodel, covparam=covparam,\n"
"    order=np.nan,\n"
"    nhmax=nhmax, nsmax=nsmax,\n"
"    dmax=np.array([[dmax]]),\n"
"    z_grid=z_grid,\n"
")\n\n"
"# z_out: shared z-grid (same as z_grid when z_grid was supplied)\n"
"# pdf_values: (nk, nz) array of PDF values; ravel gives (nz,) for nk=1\n"
"z_grid = np.asarray(z_out).ravel()\n"
"pdf_at_loc = np.asarray(pdf_values).ravel()\n"
"print(f'PDF shape: {pdf_at_loc.shape}, integral ~ {np.trapezoid(pdf_at_loc, z_grid):.3f}')\n"
))

cells.append(nbf.v4.new_code_cell(
"from scipy.stats import norm as scipy_norm\n\n"
"fig, ax = plt.subplots(figsize=(8, 4))\n"
"ax.plot(z_grid, pdf_at_loc, 'steelblue', lw=2.5, label='BME posterior PDF')\n\n"
"# Overlay Gaussian with BME mean/variance for comparison\n"
"bme_m_i = bme_mean[i_sel]\n"
"bme_v_i = bme_var[i_sel]\n"
"if not np.isnan(bme_m_i) and bme_v_i > 0:\n"
"    y_gauss = scipy_norm.pdf(z_grid, loc=bme_m_i, scale=np.sqrt(bme_v_i))\n"
"    ax.plot(z_grid, y_gauss, 'k--', lw=1.5, label='Equivalent Gaussian (BME mean/var)')\n\n"
"ax.axvline(z_true[i_sel], color='tomato',   lw=2, ls='-.',  label='True value')\n"
"ax.axvline(bme_m_i,       color='steelblue',lw=1.5, ls=':',label='BME mean')\n"
"ax.set_xlabel('Z')\n"
"ax.set_ylabel('Posterior PDF f(z)')\n"
"ax.set_title(f'Posterior PDF at estimation location {i_sel}')\n"
"ax.legend()\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 6. Credible intervals with `BMEPosteriorCI`\n\n"
"`BMEPosteriorCI` computes the Bayesian credible interval at each estimation "
"location.  A 95% credible interval $[L, U]$ means:\n\n"
"$$\\int_L^U f_k(z)\\,dz = 0.95$$\n\n"
"This is the Bayesian analogue of a confidence interval.\n"
))

cells.append(nbf.v4.new_code_cell(
"# Compute 90% credible intervals at all estimation locations\n"
"ci_levels = [0.68, 0.90, 0.99]\n\n"
"print('Running BMEPosteriorCI for credible intervals...')\n"
"ci_result = BMEPosteriorCI(\n"
"    ck_syn,\n"
"    ch=ch_syn, cs=cs_syn,\n"
"    zh=zh_syn.reshape(-1, 1),\n"
"    zs=tuple(zs_gauss),\n"
"    covmodel=covmodel, covparam=covparam,\n"
"    order=np.nan,\n"
"    nhmax=nhmax, nsmax=nsmax,\n"
"    dmax=np.array([[dmax]]),\n"
"    ci_probs=ci_levels,\n"
")\n\n"
"print(f'CI result shape: {np.array(ci_result).shape}')\n"
"# ci_result: list of (lower, upper) arrays, one per CI level\n"
))

cells.append(nbf.v4.new_code_cell(
"# Parse CI result\n"
"ci_arr = np.array(ci_result)  # (n_ci_levels, nk, 2) or similar\n"
"print('CI array shape:', ci_arr.shape)\n\n"
"# If shape is (nk, n_levels*2) or similar, adapt the indexing:\n"
"# The output depends on BMEPosteriorCI's internal structure\n"
"# Let's inspect the first result\n"
"print('First element dtype:', type(ci_result))\n"
"if isinstance(ci_result, (list, tuple)) and len(ci_result) > 0:\n"
"    print('ci_result[0] type:', type(ci_result[0]), 'shape:',\n"
"          np.array(ci_result[0]).shape if hasattr(ci_result[0], '__len__') else 'scalar')\n"
))

cells.append(nbf.v4.new_code_cell(
"# BMEPosteriorCI returns (nk, n_ci) array where each row is [lower_1, upper_1, lower_2, ...]\n"
"# Check and extract\n"
"ci_arr = np.asarray(ci_result)\n"
"print('CI array shape:', ci_arr.shape)\n\n"
"# Plot credible intervals at the selected location\n"
"i_sel2 = i_sel   # same location as PDF plot\n\n"
"fig, ax = plt.subplots(figsize=(8, 4))\n"
"ax.plot(z_grid, pdf_at_loc, 'steelblue', lw=2.5, label='BME posterior PDF')\n"
"ax.axvline(z_true[i_sel], color='tomato', lw=2, ls='-.', label='True value')\n\n"
"colors_ci = ['gold', 'orange', 'firebrick']\n"
"# Shade credible intervals\n"
"for k, (alpha_ci, col) in enumerate(zip(ci_levels, colors_ci)):\n"
"    if ci_arr.ndim >= 2 and ci_arr.shape[1] >= 2 * (k + 1):\n"
"        lo_i = ci_arr[i_sel2, 2 * k]\n"
"        hi_i = ci_arr[i_sel2, 2 * k + 1]\n"
"        if not (np.isnan(lo_i) or np.isnan(hi_i)):\n"
"            ax.axvspan(lo_i, hi_i, alpha=0.3, color=col,\n"
"                       label=f'{int(100*alpha_ci)}% CI [{lo_i:.2f}, {hi_i:.2f}]')\n"
"ax.set_xlabel('Z')\n"
"ax.set_ylabel('Posterior PDF f(z)')\n"
"ax.set_title(f'Posterior PDF with credible intervals')\n"
"ax.legend(fontsize=8)\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 7. Coverage probability verification\n\n"
"For a calibrated Bayesian model, the fraction of true values falling inside "
"a $p$-credible interval should be approximately $p$ (coverage probability).\n"
))

cells.append(nbf.v4.new_code_cell(
"print('Coverage probability verification:')\n"
"print(f'{'CI level':>12}  {'Expected':>10}  {'Observed':>10}  {'Ratio':>8}')\n"
"print('-' * 50)\n\n"
"for k, alpha_ci in enumerate(ci_levels):\n"
"    if ci_arr.ndim >= 2 and ci_arr.shape[1] >= 2 * (k + 1):\n"
"        lo = ci_arr[:, 2 * k]\n"
"        hi = ci_arr[:, 2 * k + 1]\n"
"        inside = (z_true >= lo) & (z_true <= hi) & ~np.isnan(lo)\n"
"        obs_coverage = inside.mean()\n"
"        print(f'{int(100*alpha_ci):>11}%  {alpha_ci:>10.2f}  {obs_coverage:>10.2f}  '\n"
"              f'{obs_coverage/alpha_ci:>8.2f}')\n"
))

cells.append(nbf.v4.new_code_cell(
"# Save BME results for Tutorial 07\n"
"import pickle\n\n"
"bme06_results = {\n"
"    'bme_mean':    bme_mean,\n"
"    'bme_var':     bme_var,\n"
"    'ck_syn':      ck_syn,\n"
"    'ch_syn':      ch_syn,\n"
"    'zh_syn':      zh_syn,\n"
"    'zh_full':     zh_full,\n"
"    'grid_coords': grid_coords,\n"
"    'idx_est':     idx_est,\n"
"    'idx_hard':    idx_hard,\n"
"    'idx_soft':    idx_soft,\n"
"    'cs_syn':      cs_syn,\n"
"    'zs_gauss':    zs_gauss,\n"
"    'nx': nx, 'ny': ny,\n"
"    'x_sim': x_sim, 'y_sim': y_sim,\n"
"}\n"
"save_path = os.path.join(DATA_DIR, 'tutorial06_bme.pkl')\n"
"with open(save_path, 'wb') as f:\n"
"    pickle.dump(bme06_results, f)\n"
"print('Saved:', save_path)\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 8. Summary\n\n"
"| Step | stamps_v3 function | Notes |\n"
"|---|---|---|\n"
"| Unconditional simulation | `simuchol(ch, model, param, ns)` | Generate synthetic truth |\n"
"| Gaussian soft data | `probaGaussian(zmean, zstd)` | Noisy measurements |\n"
"| BME moments | `BMEPosteriorMoments(...)` | Mean and variance |\n"
"| BME full PDF | `BMEPosteriorPDF(..., z_grid=z_grid)` | Full posterior PDF (auto-range if `z_grid` omitted) |\n"
"| Credible intervals | `BMEPosteriorCI(..., ci_probs)` | Bayesian intervals |\n\n"
"**Key insights:**\n"
"- Gaussian soft data are the continuous analogue of hard data with measurement error.\n"
"- The posterior PDF is not always Gaussian when soft data are non-Gaussian.\n"
"- Coverage probability verifies that the credible intervals are well-calibrated.\n\n"
"**Next:** Tutorial 07 - BME in the space-time domain.\n"
))

nb.cells = cells
import nbformat
with open("tutorials/06_bme_probabilistic_soft_data.ipynb", "w") as f:
    nbformat.write(nb, f)
print("Written: tutorials/06_bme_probabilistic_soft_data.ipynb")
