# -*- coding: utf-8 -*-
"""Generate 07_bme_spacetime.ipynb"""
import nbformat as nbf

nb = nbf.v4.new_notebook()
nb.metadata['kernelspec'] = {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'}
nb.metadata['language_info'] = {'name': 'python', 'version': '3.9.0'}
cells = []

cells.append(nbf.v4.new_markdown_cell(
"# Tutorial 07 - BME in the Space-Time Domain\n\n"
"**Package:** stamps_v3  \n"
"**MATLAB equivalent:** `BMEPROBALIBtutorial.m` (Part 2 - space-time domain)  \n"
"**Dataset:** Synthetic space-time dataset\n\n"
"---\n\n"
"## Learning objectives\n\n"
"1. Extend the spatial framework to **space-time** (2D space + time).\n"
"2. Build a **separable space-time covariance model** using `exponentialCST`.\n"
"3. Prepare space-time coordinates and data with `valstv2stg` / `valstg2stv`.\n"
"4. Run BME posterior moments for a specific **time slice** using `BMEPosteriorMoments`.\n"
"5. Visualise BME mean and variance maps for the target time.\n\n"
"### Space-time coordinates in stamps_v3\n\n"
"Space-time data requires **3-column coordinate arrays**: `[easting, northing, time]`.  "
"The `dmax` parameter becomes a 3-element vector `[dmax_space, dmax_time, st_ratio]`:\n\n"
"- `dmax_space` — maximum spatial search radius (metres)\n"
"- `dmax_time`  — maximum temporal search radius (time units)\n"
"- `st_ratio`   — scale factor converting time to spatial units\n"
))

cells.append(nbf.v4.new_code_cell(
"import sys, os, pickle\n"
"import numpy as np\n"
"import matplotlib.pyplot as plt\n\n"
"REPO_ROOT = os.path.abspath(os.path.join(os.getcwd(), '..'))\n"
"if REPO_ROOT not in sys.path:\n"
"    sys.path.insert(0, REPO_ROOT)\n\n"
"from stamps.stats.simulation.simulation import simuchol\n"
"from stamps.bme.softconverter import probaGaussian, probaUniform\n"
"from stamps.bme.BMEprobaEstimations import BMEPosteriorMoments\n\n"
"plt.rcParams.update({'figure.dpi': 110, 'font.size': 10})\n"
"DATA_DIR = os.path.join(os.getcwd(), 'data')\n\n"
"# Load covariance model from Tutorial 03\n"
"with open(os.path.join(DATA_DIR, 'tutorial03_cov.pkl'), 'rb') as f:\n"
"    cov = pickle.load(f)\n"
"covmodel_space = cov['sand_covmodel']\n"
"covparam_space = cov['sand_covparam']\n\n"
"print('Spatial covariance model:', covmodel_space)\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 1. Build the space-time covariance model\n\n"
"A **separable** space-time covariance model factors into the product of "
"a spatial and a temporal component:\n\n"
"$$C(h_s, h_t) = C_s(h_s) \\cdot C_t(h_t)$$\n\n"
"In stamps_v3, we express this as a **nested model** with combined metric distance:\n\n"
"$$d_{combined} = h_s + r_{st} \\cdot h_t$$\n\n"
"where $r_{st}$ converts time units to spatial units. The `exponentialCST` model "
"applies to this combined distance.\n"
))

cells.append(nbf.v4.new_code_cell(
"# Separable space-time covariance model\n"
"# For the space-time case we use non-separable CST covariance models\n"
"# and encode the space-time ratio in dmax\n\n"
"# Covariance sill and ranges from Tutorial 03 + temporal extension\n"
"c_nugget = float(covparam_space[0][0])  # nugget sill\n"
"c_sill   = float(covparam_space[1][0])  # spatial sill\n"
"a_s      = float(covparam_space[1][1])  # spatial range [m]\n\n"
"# Temporal model parameters\n"
"a_t      = 2.0      # temporal range [days]\n"
"st_ratio = a_s / a_t  # spatial-to-temporal ratio (m/day)\n\n"
"# Combined model: nugget + exponential (applied to combined s+t distance)\n"
"covmodel_st = ['nuggetC', 'exponentialCST']\n"
"covparam_st = [(c_nugget,), (c_sill, a_s)]\n\n"
"print('Space-time covariance model:', covmodel_st)\n"
"print(f'  Nugget : {c_nugget:.3f}')\n"
"print(f'  Sill   : {c_sill:.3f}')\n"
"print(f'  Spatial range : {a_s:.0f} m')\n"
"print(f'  Temporal range: {a_t:.1f} days')\n"
"print(f'  ST ratio      : {st_ratio:.1f} m/day')\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 2. Simulate a space-time dataset\n\n"
"We create a synthetic space-time field over a 10 x 10 spatial grid observed "
"at 5 time steps (Days 1-5).\n\n"
"**Implementation approach:**  \n"
"We simulate the spatial field at each time step independently using `simuchol`, "
"adding temporal correlation by a simple AR(1) model:\n\n"
"$$Z(s, t) = \\rho \\cdot Z(s, t-1) + \\sqrt{1-\\rho^2} \\cdot \\varepsilon(s, t)$$\n"
))

cells.append(nbf.v4.new_code_cell(
"rng = np.random.default_rng(seed=7)\n\n"
"# Spatial grid\n"
"nx_st, ny_st = 10, 10\n"
"x_st = np.linspace(0, 20_000, nx_st)\n"
"y_st = np.linspace(0, 14_000, ny_st)\n"
"XX_st, YY_st = np.meshgrid(x_st, y_st)\n"
"spatial_grid = np.column_stack([XX_st.ravel(), YY_st.ravel()])  # (100, 2)\n\n"
"n_space = len(spatial_grid)\n"
"n_time  = 5                     # Days 1 to 5\n"
"times   = np.arange(1, n_time + 1, dtype=float)\n\n"
"# Temporal AR(1) correlation\n"
"rho = np.exp(-1.0 / a_t)        # AR(1) coefficient\n\n"
"# Simulate using spatial Cholesky + AR(1) in time\n"
"Z_st = np.zeros((n_space, n_time))\n"
"eps0, _ = simuchol(spatial_grid, covmodel_space, covparam_space, ns=1, seed=rng)\n"
"Z_st[:, 0] = eps0[:, 0]\n"
"for t in range(1, n_time):\n"
"    eps_t, _ = simuchol(spatial_grid, covmodel_space, covparam_space, ns=1, seed=rng)\n"
"    Z_st[:, t] = rho * Z_st[:, t - 1] + np.sqrt(1 - rho**2) * eps_t[:, 0]\n\n"
"print(f'Simulated field shape: {Z_st.shape}  ({n_space} locations x {n_time} times)')\n"
"print(f'Global mean : {Z_st.mean():.4f}')\n"
"print(f'Global var  : {Z_st.var():.4f}')\n\n"
"# Plot all time slices\n"
"fig, axes = plt.subplots(1, n_time, figsize=(18, 3.5))\n"
"vz = np.percentile(np.abs(Z_st), 97)\n"
"for t_i, ax in enumerate(axes):\n"
"    Z_map = Z_st[:, t_i].reshape(ny_st, nx_st)\n"
"    im = ax.pcolormesh(x_st, y_st, Z_map, cmap='RdYlBu_r',\n"
"                       vmin=-vz, vmax=vz, shading='nearest')\n"
"    ax.set_title(f'Day {t_i+1}')\n"
"    ax.set_aspect('equal')\n"
"    if t_i == 0:\n"
"        ax.set_ylabel('Y (m)')\n"
"    ax.set_xlabel('X (m)')\n"
"plt.colorbar(im, ax=axes[-1], label='Z')\n"
"plt.suptitle('Simulated space-time field (Days 1-5)', fontsize=12, y=1.01)\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 3. Prepare space-time data\n\n"
"Hard data: exact observations at 25 randomly selected space-time points.  \n"
"Soft data: noisy Gaussian observations at 20 other space-time points.  \n"
"Estimation target: Day 3 (time = 3) over the full spatial grid.\n"
))

cells.append(nbf.v4.new_code_cell(
"# Build all space-time observations as (x, y, t) tuples\n"
"n_pts_total = n_space * n_time\n"
"# Create full space-time coordinate array\n"
"all_coords_st = []\n"
"all_vals_st   = []\n"
"for t_i, t_val in enumerate(times):\n"
"    for s_i in range(n_space):\n"
"        all_coords_st.append([spatial_grid[s_i, 0],\n"
"                              spatial_grid[s_i, 1],\n"
"                              t_val])\n"
"        all_vals_st.append(Z_st[s_i, t_i])\n"
"\n"
"all_coords_st = np.array(all_coords_st)  # (500, 3)\n"
"all_vals_st   = np.array(all_vals_st)    # (500,)\n\n"
"# Random split into hard and soft data\n"
"idx_all_st   = rng.permutation(n_pts_total)\n"
"n_hard_st    = 25\n"
"n_soft_st    = 20\n"
"idx_hard_st  = idx_all_st[:n_hard_st]\n"
"idx_soft_st  = idx_all_st[n_hard_st:n_hard_st + n_soft_st]\n\n"
"ch_st = all_coords_st[idx_hard_st]    # (n_hard, 3)\n"
"zh_st = all_vals_st[idx_hard_st]      # (n_hard,)\n"
"\n"
"cs_st = all_coords_st[idx_soft_st]    # (n_soft, 3)\n"
"noise_s = 1.5\n"
"z_soft_st_mean = all_vals_st[idx_soft_st] + rng.normal(0, noise_s, n_soft_st)\n"
"z_soft_st_std  = noise_s * np.ones(n_soft_st)\n\n"
"# Encode Gaussian soft data\n"
"zs_st = probaGaussian(z_soft_st_mean, z_soft_st_std)\n\n"
"# Estimation grid: target Day 3\n"
"target_time = 3.0\n"
"ck_st = np.column_stack([\n"
"    spatial_grid,\n"
"    target_time * np.ones(n_space)\n"
"])  # (n_space, 3)\n\n"
"# True values at target time for verification\n"
"t_idx = np.where(times == target_time)[0][0]\n"
"z_true_day3 = Z_st[:, t_idx]\n\n"
"print(f'Hard data    : {n_hard_st} space-time points')\n"
"print(f'Soft data    : {n_soft_st} space-time points')\n"
"print(f'Estimation   : {n_space} locations at Day {target_time:.0f}')\n"
))

cells.append(nbf.v4.new_code_cell(
"# Visualise data configuration for Day 3\n"
"day3_mask_h = ch_st[:, 2] == target_time\n"
"day3_mask_s = cs_st[:, 2] == target_time\n\n"
"fig, ax = plt.subplots(figsize=(8, 6))\n"
"Z_true_map = z_true_day3.reshape(ny_st, nx_st)\n"
"im = ax.pcolormesh(x_st, y_st, Z_true_map, cmap='RdYlBu_r',\n"
"                   vmin=-vz, vmax=vz, shading='nearest', alpha=0.6)\n"
"plt.colorbar(im, ax=ax, label='True Z')\n"
"ax.scatter(ch_st[day3_mask_h, 0], ch_st[day3_mask_h, 1],\n"
"           c='tomato', s=80, marker='s', edgecolors='k', lw=0.5,\n"
"           zorder=4, label='Hard data (Day 3)')\n"
"ax.scatter(ch_st[~day3_mask_h, 0], ch_st[~day3_mask_h, 1],\n"
"           c='lightcoral', s=40, marker='s', edgecolors='k', lw=0.5,\n"
"           alpha=0.5, zorder=3, label='Hard data (other days)')\n"
"ax.scatter(cs_st[day3_mask_s, 0], cs_st[day3_mask_s, 1],\n"
"           c='steelblue', s=60, marker='o', edgecolors='navy', lw=0.5,\n"
"           zorder=4, label='Soft data (Day 3)')\n"
"ax.scatter(cs_st[~day3_mask_s, 0], cs_st[~day3_mask_s, 1],\n"
"           c='lightblue', s=30, marker='o', edgecolors='navy', lw=0.5,\n"
"           alpha=0.5, zorder=3, label='Soft data (other days)')\n"
"ax.set_title('Data configuration - target: Day 3')\n"
"ax.set_aspect('equal')\n"
"ax.set_xlabel('X (m)')\n"
"ax.set_ylabel('Y (m)')\n"
"ax.legend(fontsize=8, loc='upper right')\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 4. BME posterior moments at Day 3\n\n"
"We pass the **space-time search neighbourhood** via `dmax` as a 2-element vector:\n\n"
"```python\n"
"dmax = np.array([[dmax_space, dmax_time]])\n"
"```\n\n"
"The `covmodel` is the space-time model using the CST format, and coordinates "
"are 3-column arrays `[x, y, t]`.\n"
))

cells.append(nbf.v4.new_code_cell(
"# Space-time neighbourhood parameters\n"
"nhmax_st   = 10\n"
"nsmax_st   = 8\n"
"dmax_space = 15_000.0   # 15 km spatial search\n"
"dmax_time  = 2.5        # 2.5 day temporal search\n"
"dmax_st    = np.array([[dmax_space, dmax_time]])\n\n"
"print('Running space-time BME for Day 3...')\n"
"print(f'  nhmax={nhmax_st}, nsmax={nsmax_st}')\n"
"print(f'  dmax_space={dmax_space:.0f} m, dmax_time={dmax_time:.1f} days')\n\n"
"result_st = BMEPosteriorMoments(\n"
"    ck_st,\n"
"    ch=ch_st, cs=cs_st,\n"
"    zh=zh_st.reshape(-1, 1),\n"
"    zs=tuple(zs_st),\n"
"    covmodel=covmodel_st,\n"
"    covparam=covparam_st,\n"
"    order=np.nan,\n"
"    nhmax=nhmax_st, nsmax=nsmax_st,\n"
"    dmax=dmax_st,\n"
")\n\n"
"bme_st_mean = result_st[:, 0]\n"
"bme_st_var  = result_st[:, 1]\n\n"
"valid_st = ~np.isnan(bme_st_mean)\n"
"rmse_st  = np.sqrt(np.mean((bme_st_mean[valid_st] - z_true_day3[valid_st])**2))\n"
"print(f'\\nBME estimated {valid_st.sum()} / {n_space} nodes')\n"
"print(f'RMSE vs truth: {rmse_st:.4f}')\n"
"print(f'Mean variance: {np.nanmean(bme_st_var):.4f}')\n"
))

cells.append(nbf.v4.new_code_cell(
"fig, axes = plt.subplots(1, 3, figsize=(17, 5))\n\n"
"def show_st_map(ax, z_vals, title, cmap='RdYlBu_r', vmin=None, vmax=None, cbar_label='Z'):\n"
"    Z_map = z_vals.reshape(ny_st, nx_st)\n"
"    vm = vmin if vmin is not None else np.nanpercentile(z_vals, 2)\n"
"    vx = vmax if vmax is not None else np.nanpercentile(z_vals, 98)\n"
"    im = ax.pcolormesh(x_st, y_st, Z_map, cmap=cmap,\n"
"                       vmin=vm, vmax=vx, shading='nearest')\n"
"    plt.colorbar(im, ax=ax, label=cbar_label)\n"
"    ax.set_title(title)\n"
"    ax.set_aspect('equal')\n"
"    ax.set_xlabel('X (m)')\n"
"    ax.set_ylabel('Y (m)')\n\n"
"show_st_map(axes[0], z_true_day3, 'True field - Day 3',\n"
"            vmin=-vz, vmax=vz)\n"
"show_st_map(axes[1], bme_st_mean, 'BME mean - Day 3',\n"
"            vmin=-vz, vmax=vz)\n"
"show_st_map(axes[2], bme_st_var,  'BME variance - Day 3',\n"
"            cmap='Blues', cbar_label='Variance')\n\n"
"# Mark hard/soft data at or near Day 3\n"
"for ax in axes[:2]:\n"
"    nearby_h = np.abs(ch_st[:, 2] - target_time) <= 1.5\n"
"    ax.scatter(ch_st[nearby_h, 0], ch_st[nearby_h, 1],\n"
"               c='k', s=30, marker='s', zorder=4)\n\n"
"plt.suptitle('Space-time BME estimation at Day 3', fontsize=12, y=1.01)\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 5. BME maps across multiple time slices\n\n"
"Repeat the BME estimation for each of the 5 time slices to see how the "
"estimate evolves through time.\n"
))

cells.append(nbf.v4.new_code_cell(
"fig, axes = plt.subplots(2, 5, figsize=(20, 8))\n\n"
"for t_i, t_val in enumerate(times):\n"
"    # Estimation grid for this time slice\n"
"    ck_t = np.column_stack([\n"
"        spatial_grid,\n"
"        t_val * np.ones(n_space)\n"
"    ])\n"
"    res_t = BMEPosteriorMoments(\n"
"        ck_t,\n"
"        ch=ch_st, cs=cs_st,\n"
"        zh=zh_st.reshape(-1, 1),\n"
"        zs=tuple(zs_st),\n"
"        covmodel=covmodel_st,\n"
"        covparam=covparam_st,\n"
"        order=np.nan,\n"
"        nhmax=nhmax_st, nsmax=nsmax_st,\n"
"        dmax=dmax_st,\n"
"    )\n"
"    # True field\n"
"    Z_true_t = Z_st[:, t_i]\n"
"    Z_bme_t  = res_t[:, 0]\n\n"
"    show_st_map(axes[0, t_i], Z_true_t,\n"
"                f'True - Day {int(t_val)}', vmin=-vz, vmax=vz)\n"
"    show_st_map(axes[1, t_i], Z_bme_t,\n"
"                f'BME mean - Day {int(t_val)}', vmin=-vz, vmax=vz)\n\n"
"plt.suptitle('Space-time BME: true field vs. estimates (all days)', fontsize=12, y=1.01)\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 6. Effect of temporal neighbourhood\n\n"
"The temporal search radius `dmax_time` controls how much past and future "
"observations influence the estimate.  A larger temporal window improves "
"the estimate in areas with sparse data but may over-smooth temporal dynamics.\n"
))

cells.append(nbf.v4.new_code_cell(
"dmax_time_vals = [1.0, 2.5, 5.0]\n"
"fig, axes = plt.subplots(1, 3, figsize=(17, 5))\n\n"
"for ax, dt_val in zip(axes, dmax_time_vals):\n"
"    res_dt = BMEPosteriorMoments(\n"
"        ck_st,\n"
"        ch=ch_st, cs=cs_st,\n"
"        zh=zh_st.reshape(-1, 1),\n"
"        zs=tuple(zs_st),\n"
"        covmodel=covmodel_st,\n"
"        covparam=covparam_st,\n"
"        order=np.nan,\n"
"        nhmax=nhmax_st, nsmax=nsmax_st,\n"
"        dmax=np.array([[dmax_space, dt_val]]),\n"
"    )\n"
"    rmse_dt = np.sqrt(np.nanmean((res_dt[:, 0] - z_true_day3)**2))\n"
"    show_st_map(ax, res_dt[:, 0],\n"
"                f'dmax_time={dt_val:.1f} d  RMSE={rmse_dt:.3f}',\n"
"                vmin=-vz, vmax=vz)\n\n"
"plt.suptitle('Effect of temporal search window (Day 3)', fontsize=12, y=1.01)\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 7. Summary\n\n"
"| Concept | stamps_v3 implementation |\n"
"|---|---|\n"
"| 3-D coordinates | `[x, y, t]` as 3-column array |\n"
"| Space-time covariance | `exponentialCST` + `nuggetC` |\n"
"| Space-time neighbourhood | `dmax = [[dmax_space, dmax_time]]` |\n"
"| BME estimation | Same `BMEPosteriorMoments` as spatial case |\n\n"
"**Key insights:**\n"
"- The space-time BME framework is a direct generalisation of the spatial case.\n"
"- The CST covariance models apply to a combined spatial+temporal metric.\n"
"- Data from nearby times (within `dmax_time`) are used as temporal neighbours.\n"
"- Increasing `dmax_time` borrows more information across time, reducing variance "
"  but potentially smoothing sharp temporal transitions.\n\n"
"**Next:** Tutorial 08 - Random field simulation.\n"
))

nb.cells = cells
import nbformat
with open("tutorials/07_bme_spacetime.ipynb", "w") as f:
    nbformat.write(nb, f)
print("Written: tutorials/07_bme_spacetime.ipynb")
