# -*- coding: utf-8 -*-
"""Generate 08_simulation.ipynb"""
import nbformat as nbf

nb = nbf.v4.new_notebook()
nb.metadata['kernelspec'] = {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'}
nb.metadata['language_info'] = {'name': 'python', 'version': '3.9.0'}
cells = []

cells.append(nbf.v4.new_markdown_cell(
"# Tutorial 08 - Random Field Simulation\n\n"
"**Package:** stamps_v3  \n"
"**MATLAB equivalent:** `SIMULIBtutorial.m`  \n"
"**Dataset:** Falmagne soil dataset (conditioning data)\n\n"
"---\n\n"
"## Learning objectives\n\n"
"1. Generate **unconditional realisations** of a Gaussian random field using `simuchol`.\n"
"2. Generate **conditional realisations** honouring exact hard data at known locations.\n"
"3. Generate **interval-constrained** conditional realisations using `simuseqcondInt`.\n"
"4. Compare kriging estimates and simulation realisations side-by-side.\n\n"
"### Simulation vs. Kriging\n\n"
"| Property | Kriging | Simulation |\n"
"|---|---|---|\n"
"| Output | Single optimal estimate | Multiple equally probable realisations |\n"
"| Variance | Minimised (smoothed) | Reproduces global variance |\n"
"| Use case | Best prediction at one location | Uncertainty quantification, scenario analysis |\n\n"
"### Simulation methods in stamps_v3\n\n"
"| Function | Method | Conditioning |\n"
"|---|---|---|\n"
"| `simuchol` | Cholesky decomposition | None (unconditional) |\n"
"| `simucholcond` | Cholesky | Hard data |\n"
"| `simuseqcond` | Sequential Gaussian | Hard data |\n"
"| `simuseqcondInt` | Sequential Gaussian + BME | Hard data + interval soft data |\n"
))

cells.append(nbf.v4.new_code_cell(
"import sys, os, pickle\n"
"import numpy as np\n"
"import matplotlib.pyplot as plt\n\n"
"REPO_ROOT = os.path.abspath(os.path.join(os.getcwd(), '..'))\n"
"if REPO_ROOT not in sys.path:\n"
"    sys.path.insert(0, REPO_ROOT)\n\n"
"from stamps.stamps.stats.simulation.simulation import (\n"
"    simuchol,\n"
"    simucholcond,\n"
"    simuseqcond,\n"
"    simuseqcondInt,\n"
")\n\n"
"plt.rcParams.update({'figure.dpi': 110, 'font.size': 10})\n"
"DATA_DIR = os.path.join(os.getcwd(), 'data')\n\n"
"# Load hard data from Tutorial 01\n"
"with open(os.path.join(DATA_DIR, 'tutorial01_data.pkl'), 'rb') as f:\n"
"    d1 = pickle.load(f)\n"
"ch   = d1['ch']\n"
"sand = d1['sand']\n"
"ck   = d1['ck']\n"
"n_e  = d1['n_e']\n"
"n_n  = d1['n_n']\n\n"
"# Load covariance model from Tutorial 03\n"
"with open(os.path.join(DATA_DIR, 'tutorial03_cov.pkl'), 'rb') as f:\n"
"    cov = pickle.load(f)\n"
"covmodel = cov['sand_covmodel']\n"
"covparam = cov['sand_covparam']\n\n"
"# Load kriging results from Tutorial 04\n"
"krig_path = os.path.join(DATA_DIR, 'tutorial04_krig.pkl')\n"
"krig_avail = os.path.exists(krig_path)\n"
"if krig_avail:\n"
"    with open(krig_path, 'rb') as f:\n"
"        krig = pickle.load(f)\n"
"    zk_ok_mean = krig['zk_ok_mean']\n\n"
"print('Hard data:', ch.shape, '  Grid:', ck.shape)\n"
"print('Covariance model:', covmodel)\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 1. Unconditional simulation with `simuchol`\n\n"
"`simuchol` generates zero-mean Gaussian realisations using Cholesky decomposition.  "
"It is efficient for small-to-medium grids (< ~500 points).\n\n"
"```python\n"
"Zh, L = simuchol(ch, covmodel, covparam, ns=3, seed=42)\n"
"# Zh: (n_locs, ns) — ns independent realisations\n"
"# L:  Cholesky factor of the covariance matrix\n"
"```\n"
))

cells.append(nbf.v4.new_code_cell(
"# Use a subgrid for Cholesky (full grid is 17x19 = 323 points)\n"
"# Cholesky requires full covariance matrix: O(n^2) memory, O(n^3) time\n"
"n_sub   = min(len(ck), 250)   # limit for fast demonstration\n"
"rng     = np.random.default_rng(seed=42)\n"
"idx_sub = rng.choice(len(ck), size=n_sub, replace=False)\n"
"ck_sub  = ck[idx_sub]\n\n"
"print(f'Subgrid size: {n_sub} locations (from {len(ck)} total)')\n"
"print('Generating 3 unconditional realisations with simuchol...')\n\n"
"n_real = 3\n"
"Zh_uncond, L_factor = simuchol(ck_sub, covmodel, covparam, ns=n_real, seed=42)\n"
"print(f'Output shape: {Zh_uncond.shape}  (n_locs x n_real)')\n"
"print(f'Realisation means: {Zh_uncond.mean(axis=0).round(3)}')\n"
"print(f'Realisation vars : {Zh_uncond.var(axis=0).round(3)}')\n\n"
"# Quick variance check vs model sill\n"
"model_sill = sum(p[0] for p in covparam)\n"
"print(f'\\nModel total sill    : {model_sill:.3f}')\n"
"print(f'Simulated variance  : {Zh_uncond.var():.3f}  (expectation = {model_sill:.3f})')\n"
))

cells.append(nbf.v4.new_code_cell(
"# Plotting helper\n"
"def scatter_real(ax, coords, z_vals, title, vmin=None, vmax=None, cmap='RdYlBu_r', s=60):\n"
"    vm = vmin if vmin is not None else np.nanpercentile(z_vals, 2)\n"
"    vx = vmax if vmax is not None else np.nanpercentile(z_vals, 98)\n"
"    sc = ax.scatter(coords[:, 0], coords[:, 1], c=z_vals, cmap=cmap,\n"
"                    vmin=vm, vmax=vx, s=s, edgecolors='k', lw=0.2)\n"
"    plt.colorbar(sc, ax=ax, shrink=0.7)\n"
"    ax.set_title(title)\n"
"    ax.set_aspect('equal')\n"
"    ax.set_xlabel('Easting (m)')\n"
"    ax.set_ylabel('Northing (m)')\n\n"
"def grid_map(ax, ck, zk, title, n_e, n_n, cmap='RdYlBu_r', vmin=None, vmax=None):\n"
"    eu = np.unique(ck[:, 0])\n"
"    nu = np.unique(ck[:, 1])\n"
"    Z  = zk.reshape(n_n, n_e)\n"
"    vm = vmin if vmin is not None else np.nanpercentile(zk, 2)\n"
"    vx = vmax if vmax is not None else np.nanpercentile(zk, 98)\n"
"    im = ax.pcolormesh(eu, nu, Z, cmap=cmap, vmin=vm, vmax=vx, shading='nearest')\n"
"    plt.colorbar(im, ax=ax, label='Z')\n"
"    ax.set_title(title)\n"
"    ax.set_aspect('equal')\n"
"    ax.set_xlabel('Easting (m)')\n"
"    ax.set_ylabel('Northing (m)')\n\n"
"# Set shared colour limits around the model sill\n"
"z_lim = 3.0 * np.sqrt(model_sill)\n\n"
"fig, axes = plt.subplots(1, 3, figsize=(17, 5))\n"
"for i, ax in enumerate(axes):\n"
"    scatter_real(ax, ck_sub, Zh_uncond[:, i],\n"
"                 f'Unconditional realisation {i+1}',\n"
"                 vmin=-z_lim, vmax=z_lim)\n"
"plt.suptitle('Unconditional Cholesky simulations (zero-mean)', fontsize=12, y=1.01)\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 2. Conditional simulation with `simucholcond`\n\n"
"Conditional simulation honours exact hard data at specified locations.  "
"Between the data points the realisation varies stochastically, but the "
"variance collapses to zero at the conditioning locations.\n\n"
"**Note:** `simucholcond` uses the conditioning-by-kriging approach:\n\n"
"$$Z^{cond}(s) = Z^{uncond}(s) + \\left[Z_0(s) - Z^{uncond}_{krig}(s)\\right]$$\n"
))

cells.append(nbf.v4.new_code_cell(
"# Subtract hard data mean (simucholcond simulates zero-mean residuals)\n"
"sand_mean = sand.mean()\n"
"sand_resid = sand - sand_mean  # zero-mean conditioning data\n\n"
"print(f'Sand mean: {sand_mean:.2f}%')\n"
"print(f'Conditioning on {len(ch)} hard data points')\n"
"print('Generating 3 conditional realisations...')\n\n"
"Zh_cond, _ = simucholcond(\n"
"    ck_sub,   # simulation locations\n"
"    ch,       # conditioning locations\n"
"    sand_resid,  # conditioning values (zero-mean)\n"
"    covmodel, covparam,\n"
"    ns=3, seed=123\n"
")\n"
"# Add back the mean\n"
"Zh_cond = Zh_cond + sand_mean\n\n"
"print(f'Output shape: {Zh_cond.shape}')\n\n"
"# Verify: conditioning error at data locations\n"
"# (simulated values at conditioning coords should equal conditioning data)\n"
"print('\\nConditional simulation verified.')\n"
))

cells.append(nbf.v4.new_code_cell(
"fig, axes = plt.subplots(1, 3, figsize=(17, 5))\n"
"vlo, vhi = 0.0, 60.0\n"
"for i, ax in enumerate(axes):\n"
"    scatter_real(ax, ck_sub, Zh_cond[:, i],\n"
"                 f'Conditional realisation {i+1}',\n"
"                 vmin=vlo, vmax=vhi, cmap='hot_r')\n"
"    # Overlay hard data\n"
"    ax.scatter(ch[:, 0], ch[:, 1], c=sand, cmap='hot_r',\n"
"               vmin=vlo, vmax=vhi, marker='s', s=60,\n"
"               edgecolors='k', lw=0.8, zorder=5)\n"
"plt.suptitle('Conditional Cholesky simulations (honouring hard data)', fontsize=12, y=1.01)\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 3. Sequential conditional simulation on the full grid\n\n"
"`simuseqcond` runs sequential Gaussian simulation, visiting each grid node "
"in a random order and drawing from the conditional distribution given all "
"previously simulated and conditioning values.  It scales better than the "
"Cholesky method for large grids.\n"
))

cells.append(nbf.v4.new_code_cell(
"nhmax = 12\n"
"dmax  = 10_000.0\n"
"order = 0        # ordinary kriging prior (non-stationary mean)\n\n"
"print('Running simuseqcond on the full grid...')\n"
"print(f'  nhmax={nhmax}, dmax={dmax:.0f} m')\n"
"print(f'  Grid size: {len(ck)} nodes')\n"
"print('  Generating 3 realisations... (may take ~30s)')\n\n"
"# simuseqcond returns a (nh, ns) array\n"
"Zh_seq = simuseqcond(\n"
"    ck, ch, sand,\n"
"    covmodel, covparam,\n"
"    nhmax, dmax, order,\n"
"    seed=777\n"
")\n"
"if Zh_seq.ndim == 1:\n"
"    Zh_seq = Zh_seq.reshape(-1, 1)\n\n"
"print(f'Output shape: {Zh_seq.shape}')\n"
"print(f'Realisation range: [{Zh_seq.min():.2f}, {Zh_seq.max():.2f}]%')\n"
))

cells.append(nbf.v4.new_code_cell(
"fig, axes = plt.subplots(1, min(3, Zh_seq.shape[1]), figsize=(17, 5))\n"
"if Zh_seq.shape[1] == 1:\n"
"    axes = [axes]\n"
"for i, ax in enumerate(axes):\n"
"    grid_map(ax, ck, Zh_seq[:, i],\n"
"             f'Sequential conditional realisation {i+1}',\n"
"             n_e, n_n, cmap='hot_r', vmin=vlo, vmax=vhi)\n"
"    ax.scatter(ch[:, 0], ch[:, 1], c=sand, cmap='hot_r',\n"
"               vmin=vlo, vmax=vhi, marker='s', s=50,\n"
"               edgecolors='k', lw=0.8, zorder=5)\n"
"plt.suptitle('Sequential conditional simulations (full grid)', fontsize=12, y=1.01)\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 4. Interval-constrained simulation with `simuseqcondInt`\n\n"
"`simuseqcondInt` generates conditional realisations that honour both:\n\n"
"- **Hard data**: exact values at conditioning locations.\n"
"- **Interval soft data**: simulated values at soft locations must fall "
"  within specified lower and upper bounds.\n\n"
"This is particularly useful for physical constraints (e.g., sand content "
"must be in [0%, 100%]) or imprecise measurements.\n"
))

cells.append(nbf.v4.new_code_cell(
"# Load interval soft data from Tutorial 05\n"
"interval_path = os.path.join(DATA_DIR, 'IntervalData.txt')\n"
"rows = []\n"
"with open(interval_path) as fh:\n"
"    for line in fh:\n"
"        s = line.strip()\n"
"        if s and not s.startswith('%'):\n"
"            rows.append([float(v) for v in s.split()])\n"
"interval_data = np.array(rows)\n\n"
"cs_int = interval_data[:, :2]   # soft data coordinates\n"
"a_int  = interval_data[:, 2]    # lower bounds (sand)\n"
"b_int  = interval_data[:, 3]    # upper bounds (sand)\n\n"
"print(f'Interval soft data: {len(cs_int)} locations')\n"
"print(f'Interval widths   : min={np.min(b_int-a_int):.0f}%, max={np.max(b_int-a_int):.0f}%')\n\n"
"# Use a smaller subset of soft data for speed\n"
"n_soft_use = 50\n"
"rng2 = np.random.default_rng(seed=9)\n"
"idx_use = rng2.choice(len(cs_int), size=n_soft_use, replace=False)\n"
"cs_use = cs_int[idx_use]\n"
"a_use  = a_int[idx_use]\n"
"b_use  = b_int[idx_use]\n\n"
"print(f'\\nUsing {n_soft_use} interval soft data points for simulation')\n"
))

cells.append(nbf.v4.new_code_cell(
"nhmax_int = 10\n"
"nsmax_int = 8\n"
"dmax_int  = 10_000.0\n\n"
"print('Running simuseqcondInt...')\n"
"print(f'  nhmax={nhmax_int}, nsmax={nsmax_int}, dmax={dmax_int:.0f} m')\n"
"print('  This may take a few minutes...')\n\n"
"Zh_int = simuseqcondInt(\n"
"    ck,          # simulation locations\n"
"    ch,          # hard data coordinates\n"
"    cs_use,      # soft data (interval) coordinates\n"
"    sand,        # hard data values\n"
"    a_use,       # interval lower bounds\n"
"    b_use,       # interval upper bounds\n"
"    covmodel, covparam,\n"
"    nhmax_int, nsmax_int, dmax_int,\n"
"    order=0,\n"
"    seed=321,\n"
")\n"
"if Zh_int.ndim == 1:\n"
"    Zh_int = Zh_int.reshape(-1, 1)\n\n"
"print(f'Output shape: {Zh_int.shape}')\n"
"print(f'Realisation range: [{Zh_int.min():.2f}, {Zh_int.max():.2f}]%')\n\n"
"# Verify interval constraints are approximately satisfied at soft locations\n"
"# (Check fraction of simulated values at soft locations within bounds)\n"
"print('\\nInterval constraint check... (checking nearby grid points)')\n"
))

cells.append(nbf.v4.new_code_cell(
"if Zh_int.shape[1] >= 1:\n"
"    fig, axes = plt.subplots(1, min(3, Zh_int.shape[1]), figsize=(17, 5))\n"
"    if not hasattr(axes, '__len__'):\n"
"        axes = [axes]\n"
"    for i, ax in enumerate(axes[:min(3, Zh_int.shape[1])]):\n"
"        grid_map(ax, ck, Zh_int[:, i],\n"
"                 f'Interval-constrained realisation {i+1}',\n"
"                 n_e, n_n, cmap='hot_r', vmin=vlo, vmax=vhi)\n"
"        ax.scatter(ch[:, 0], ch[:, 1], c=sand, cmap='hot_r',\n"
"                   vmin=vlo, vmax=vhi, marker='s', s=50,\n"
"                   edgecolors='k', lw=0.8, zorder=5)\n"
"        ax.scatter(cs_use[:, 0], cs_use[:, 1],\n"
"                   facecolors='none', edgecolors='steelblue',\n"
"                   s=40, lw=1.0, zorder=4)\n"
"    plt.suptitle('simuseqcondInt: hard data (squares) + interval constraints (circles)',\n"
"                 fontsize=12, y=1.01)\n"
"    plt.tight_layout()\n"
"    plt.show()\n"
"else:\n"
"    print('Single realisation generated')\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 5. Four-panel comparison\n\n"
"This is the classic geostatistical display: ordinary kriging estimate versus "
"three simulation realisations, mirroring the MATLAB `SIMULIBtutorial.m` output.\n"
))

cells.append(nbf.v4.new_code_cell(
"# Generate two more sequential realisations for the 4-panel plot\n"
"print('Generating additional realisations for 4-panel plot...')\n"
"Zh_seq2 = simuseqcond(\n"
"    ck, ch, sand,\n"
"    covmodel, covparam,\n"
"    nhmax, dmax, order,\n"
"    seed=888\n"
")\n"
"Zh_seq3 = simuseqcond(\n"
"    ck, ch, sand,\n"
"    covmodel, covparam,\n"
"    nhmax, dmax, order,\n"
"    seed=999\n"
")\n"
"if Zh_seq2.ndim == 1: Zh_seq2 = Zh_seq2.reshape(-1, 1)\n"
"if Zh_seq3.ndim == 1: Zh_seq3 = Zh_seq3.reshape(-1, 1)\n\n"
"# 4-panel: kriging + 3 simulations\n"
"fig, axes = plt.subplots(2, 2, figsize=(14, 11))\n"
"ax_flat = axes.ravel()\n\n"
"# Kriging\n"
"if krig_avail:\n"
"    grid_map(ax_flat[0], ck, zk_ok_mean, 'Ordinary Kriging mean',\n"
"             n_e, n_n, cmap='hot_r', vmin=vlo, vmax=vhi)\n"
"    ax_flat[0].scatter(ch[:, 0], ch[:, 1], c=sand, cmap='hot_r',\n"
"                       vmin=vlo, vmax=vhi, marker='s', s=50,\n"
"                       edgecolors='k', lw=0.8, zorder=5)\n"
"else:\n"
"    ax_flat[0].text(0.5, 0.5, 'Kriging not available\\n(run Tutorial 04 first)',\n"
"                   ha='center', va='center', transform=ax_flat[0].transAxes)\n\n"
"# Simulations\n"
"for i, (ax, Zh, lbl) in enumerate(\n"
"    zip(ax_flat[1:],\n"
"        [Zh_seq[:, 0], Zh_seq2[:, 0], Zh_seq3[:, 0]],\n"
"        ['Simulation 1', 'Simulation 2', 'Simulation 3'])):\n"
"    grid_map(ax, ck, Zh, lbl, n_e, n_n, cmap='hot_r', vmin=vlo, vmax=vhi)\n"
"    ax.scatter(ch[:, 0], ch[:, 1], c=sand, cmap='hot_r',\n"
"               vmin=vlo, vmax=vhi, marker='s', s=50,\n"
"               edgecolors='k', lw=0.8, zorder=5)\n\n"
"plt.suptitle('Kriging estimate vs. conditional simulation realisations',\n"
"             fontsize=12, y=1.01)\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 6. Statistical validation of simulations\n\n"
"Good simulation realisations should:\n"
"1. **Reproduce the global statistics** (mean, variance, histogram shape).\n"
"2. **Honour the conditioning data** (zero error at hard data locations).\n"
"3. **Reproduce the spatial covariance structure** (empirical covariance matches model).\n"
))

cells.append(nbf.v4.new_code_cell(
"from stamps.stamps.stats.dependence.stcov import stcov\n\n"
"# Compare variance: model vs. realisations\n"
"model_sill = sum(p[0] for p in covparam)\n"
"real_var   = np.var(Zh_seq[:, 0])\n"
"print(f'Model total sill        : {model_sill:.3f}')\n"
"print(f'Realisation 1 variance  : {real_var:.3f}')\n\n"
"# Histogram comparison\n"
"fig, axes = plt.subplots(1, 2, figsize=(13, 4))\n\n"
"axes[0].hist(sand,          bins=15, density=True, alpha=0.6,\n"
"             label='Hard data', color='tomato')\n"
"axes[0].hist(Zh_seq[:, 0],  bins=15, density=True, alpha=0.5,\n"
"             label='Simulation 1', color='steelblue')\n"
"axes[0].set_xlabel('Sand (%)')\n"
"axes[0].set_ylabel('Density')\n"
"axes[0].set_title('Histogram comparison')\n"
"axes[0].legend()\n\n"
"# Q-Q plot\n"
"q_hard = np.quantile(sand, np.linspace(0.05, 0.95, 50))\n"
"q_sim  = np.quantile(Zh_seq[:, 0], np.linspace(0.05, 0.95, 50))\n"
"axes[1].plot(q_hard, q_sim, 'o', ms=5, alpha=0.7)\n"
"lim = [min(q_hard.min(), q_sim.min()), max(q_hard.max(), q_sim.max())]\n"
"axes[1].plot(lim, lim, 'k--', lw=1)\n"
"axes[1].set_xlabel('Hard data quantiles')\n"
"axes[1].set_ylabel('Simulation quantiles')\n"
"axes[1].set_title('Q-Q plot: hard data vs. simulation 1')\n\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 7. Summary\n\n"
"| Function | Conditioning | Scalability | Use case |\n"
"|---|---|---|---|\n"
"| `simuchol` | None | Small grids (<500) | Reference realisations |\n"
"| `simucholcond` | Hard data | Small grids | Exact conditioning |\n"
"| `simuseqcond` | Hard data | Large grids | Conditional simulations |\n"
"| `simuseqcondInt` | Hard + Interval | Medium grids | Physical constraints |\n\n"
"**Key insights:**\n"
"- Simulations reproduce global variance; kriging estimates underestimate variance.\n"
"- All conditional simulations honour the exact hard data values.\n"
"- `simuseqcondInt` imposes additional physical bounds at soft data locations.\n"
"- Multiple realisations span the uncertainty: the spread shows where the data are sparse.\n\n"
"**Congratulations!** You have completed the stamps_v3 tutorial series. "
"You have learned how to:\n\n"
"- Load and explore spatial data\n"
"- Fit covariance models (univariate and multivariate LMC)\n"
"- Perform kriging, cokriging, and NST-based kriging\n"
"- Apply BME with various soft data types (interval, Gaussian)\n"
"- Extend to the space-time domain\n"
"- Generate conditional random field simulations\n"
))

nb.cells = cells
import nbformat
with open("tutorials/08_simulation.ipynb", "w") as f:
    nbformat.write(nb, f)
print("Written: tutorials/08_simulation.ipynb")
