# -*- coding: utf-8 -*-
"""Generate 05_bme_interval_soft_data.ipynb"""
import nbformat as nbf

nb = nbf.v4.new_notebook()
nb.metadata['kernelspec'] = {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'}
nb.metadata['language_info'] = {'name': 'python', 'version': '3.9.0'}
cells = []

cells.append(nbf.v4.new_markdown_cell(
"# Tutorial 05 - BME with Interval (Soft) Data\n\n"
"**Package:** stamps_v3  \n"
"**MATLAB equivalent:** `BMEINTLIBtutorial.m`  \n"
"**Dataset:** Falmagne interval dataset (`IntervalData.txt`)\n\n"
"---\n\n"
"## Learning objectives\n\n"
"1. Load and explore the Falmagne **interval soft data** dataset.\n"
"2. Encode interval observations as **uniform soft PDFs** with `probaUniform`.\n"
"3. Run **BME posterior-moments** estimation with `BMEPosteriorMoments`.\n"
"4. Compare the BME result to the ordinary kriging estimate from Tutorial 04.\n\n"
"### What is interval (soft) data?\n\n"
"Instead of knowing the exact sand content at a location, we know only that "
"it falls within an interval $[z^{lo}, z^{up}]$.  "
"BME encodes this as a **uniform probability density** over the interval.\n\n"
"$$f(z) = \\begin{cases} \\frac{1}{z^{up} - z^{lo}} & z^{lo} \\le z \\le z^{up} \\\\\n"
"         0 & \\text{otherwise} \\end{cases}$$\n\n"
"This is a *soft* measurement: less informative than a precise value "
"but more informative than knowing nothing.\n"
))

cells.append(nbf.v4.new_code_cell(
"import sys, os, pickle\n"
"import numpy as np\n"
"import matplotlib.pyplot as plt\n\n"
"REPO_ROOT = os.path.abspath(os.path.join(os.getcwd(), '..'))\n"
"if REPO_ROOT not in sys.path:\n"
"    sys.path.insert(0, REPO_ROOT)\n\n"
"from stamps.bme.softconverter import probaUniform, proba2stat\n"
"from stamps.bme.BMEprobaEstimations import BMEPosteriorMoments\n\n"
"plt.rcParams.update({'figure.dpi': 110, 'font.size': 10})\n"
"DATA_DIR = os.path.join(os.getcwd(), 'data')\n\n"
"# Load hard data and grid from Tutorial 01\n"
"with open(os.path.join(DATA_DIR, 'tutorial01_data.pkl'), 'rb') as f:\n"
"    d1 = pickle.load(f)\n"
"ch   = d1['ch']\n"
"sand = d1['sand']\n"
"ck   = d1['ck']\n"
"n_e  = d1['n_e']\n"
"n_n  = d1['n_n']\n\n"
"# Load covariance model from Tutorial 03\n"
"with open(os.path.join(DATA_DIR, 'tutorial03_cov.pkl'), 'rb') as f:\n"
"    cov = pickle.load(f)\n"
"covmodel = cov['sand_covmodel']\n"
"covparam = cov['sand_covparam']\n\n"
"# Load kriging results from Tutorial 04 (for comparison)\n"
"krig_path = os.path.join(DATA_DIR, 'tutorial04_krig.pkl')\n"
"krig_available = os.path.exists(krig_path)\n"
"if krig_available:\n"
"    with open(krig_path, 'rb') as f:\n"
"        krig = pickle.load(f)\n"
"    zk_ok_mean = krig['zk_ok_mean']\n"
"    zk_ok_var  = krig['zk_ok_var']\n"
"    print('Kriging results loaded.')\n\n"
"print('Hard data:', ch.shape, '  Grid:', ck.shape)\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 1. Load the interval dataset\n\n"
"The `IntervalData.txt` file contains 323 soil samples where the sand, silt "
"and clay contents are given as intervals of width 20% "
"(e.g., sand in [20%, 40%]).\n"
))

cells.append(nbf.v4.new_code_cell(
"# Read interval data (skip % comment lines)\n"
"interval_path = os.path.join(DATA_DIR, 'IntervalData.txt')\n"
"rows = []\n"
"with open(interval_path) as fh:\n"
"    for line in fh:\n"
"        s = line.strip()\n"
"        if s and not s.startswith('%'):\n"
"            rows.append([float(v) for v in s.split()])\n\n"
"data = np.array(rows)   # (323, 8)\n"
"cs      = data[:, :2]   # easting, northing\n"
"s_lo    = data[:, 2]    # sand lower bound (%)\n"
"s_hi    = data[:, 3]    # sand upper bound (%)\n\n"
"print(f'Interval soft data: {cs.shape[0]} locations')\n"
"print(f'Sand interval range: [{s_lo.min():.0f}, {s_hi.max():.0f}] %')\n"
"print(f'Mean interval width: {np.mean(s_hi - s_lo):.1f} %')\n\n"
"# Easting / Northing extents\n"
"e_range = cs[:, 0].min(), cs[:, 0].max()\n"
"n_range = cs[:, 1].min(), cs[:, 1].max()\n"
"print(f'Easting : {e_range[0]:.0f} -- {e_range[1]:.0f} m')\n"
"print(f'Northing: {n_range[0]:.0f} -- {n_range[1]:.0f} m')\n"
))

cells.append(nbf.v4.new_code_cell(
"# Visualise hard data and soft data locations\n"
"mid_sand = 0.5 * (s_lo + s_hi)  # interval midpoints for colour coding\n\n"
"fig, ax = plt.subplots(figsize=(8, 7))\n"
"# Soft data: circles sized by interval width\n"
"widths = s_hi - s_lo\n"
"sc_soft = ax.scatter(cs[:, 0], cs[:, 1],\n"
"                     c=mid_sand, cmap='hot_r', vmin=0, vmax=60,\n"
"                     s=100 + 8 * widths, alpha=0.6,\n"
"                     edgecolors='steelblue', linewidths=1.0, label='Interval (soft)')\n"
"# Hard data: filled squares\n"
"sc_hard = ax.scatter(ch[:, 0], ch[:, 1],\n"
"                     c=sand, cmap='hot_r', vmin=0, vmax=60,\n"
"                     marker='s', s=50, edgecolors='k', linewidths=0.8,\n"
"                     label='Exact (hard)')\n"
"plt.colorbar(sc_soft, ax=ax, label='Sand midpoint (%)')\n"
"ax.set_title('Falmagne - Hard data (squares) and interval soft data (circles)')\n"
"ax.set_xlabel('Easting (m)')\n"
"ax.set_ylabel('Northing (m)')\n"
"ax.set_aspect('equal')\n"
"ax.legend()\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 2. Encode intervals as uniform soft PDFs\n\n"
"`probaUniform` converts lower/upper bounds into the standard stamps soft-data format:\n\n"
"```python\n"
"zs = probaUniform(zlow, zup)\n"
"# Returns: [softpdftype=2, nl, limi, probdens]\n"
"#   softpdftype : 2 = piecewise-linear PDF\n"
"#   nl          : (ns, 1) number of limit points per location\n"
"#   limi        : (ns, 2) lower and upper bounds\n"
"#   probdens    : (ns, 2) constant probability density\n"
"```\n"
))

cells.append(nbf.v4.new_code_cell(
"# Encode sand intervals as uniform soft PDFs\n"
"zs_soft = probaUniform(s_lo, s_hi)\n"
"softpdftype, nl, limi, probdens = zs_soft\n\n"
"print(f'softpdftype : {softpdftype}')\n"
"print(f'nl shape    : {nl.shape}  (first 5: {nl[:5, 0]})')\n"
"print(f'limi shape  : {limi.shape}')\n"
"print(f'probdens shape: {probdens.shape}')\n"
"print('\\nFirst 5 soft data records:')\n"
"for i in range(5):\n"
"    lo, hi = limi[i]\n"
"    pd = probdens[i, 0]\n"
"    print(f'  [{lo:.1f}, {hi:.1f}]  -> pdf = {pd:.4f}')\n"
))

cells.append(nbf.v4.new_code_cell(
"# Compute soft data summary statistics\n"
"soft_mean, soft_var = proba2stat(softpdftype, nl, limi, probdens)\n\n"
"print('Soft data summary (sand %)')\n"
"print(f'  Mean of soft means : {np.mean(soft_mean):.2f}%')\n"
"print(f'  Mean of soft vars  : {np.mean(soft_var):.2f}')\n"
"print(f'  Hard data mean     : {np.mean(sand):.2f}%')\n"
"print(f'  Hard data var      : {np.var(sand):.2f}')\n\n"
"# Plot distribution of soft data means vs hard data values\n"
"fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n"
"axes[0].hist(sand,       bins=15, alpha=0.7, label='Hard data', color='steelblue')\n"
"axes[0].hist(soft_mean,  bins=15, alpha=0.6, label='Soft midpoints', color='tomato')\n"
"axes[0].set_xlabel('Sand (%)')\n"
"axes[0].set_ylabel('Count')\n"
"axes[0].set_title('Distribution comparison')\n"
"axes[0].legend()\n\n"
"axes[1].scatter(soft_mean, np.sqrt(soft_var), alpha=0.5, s=20, color='tomato')\n"
"axes[1].set_xlabel('Soft data mean (%)')\n"
"axes[1].set_ylabel('Soft data std dev (%)')\n"
"axes[1].set_title('Soft data: mean vs. std dev')\n\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 3. BME posterior moments estimation\n\n"
"We now run `BMEPosteriorMoments` combining:\n\n"
"- **Hard data** at 118 precise locations (`ch`, `zh`).\n"
"- **Interval soft data** at 323 additional locations (`cs`, `zs`).\n"
"- **Prior covariance** model (nugget + spherical) fitted in Tutorial 03.\n\n"
"The posterior BME estimate at each grid node is computed as:\n\n"
"$$\\hat{z}^{BME}_k = \\int z \\cdot f_k(z | \\text{data}) \\, dz$$\n\n"
"where $f_k$ is the posterior PDF at node $k$, updated from the prior using Bayes' theorem.\n"
))

cells.append(nbf.v4.new_code_cell(
"# BME options\n"
"nhmax = 12    # max hard data neighbours\n"
"nsmax = 8     # max soft data neighbours\n"
"dmax  = 10_000.0  # 10 km search radius\n"
"order = np.nan     # ordinary kriging prior\n\n"
"# Run BME posterior moments\n"
"print('Running BMEPosteriorMoments with interval soft data...')\n"
"print(f'  nhmax={nhmax}, nsmax={nsmax}, dmax={dmax:.0f} m')\n"
"print('  This may take a minute...')\n\n"
"result = BMEPosteriorMoments(\n"
"    ck,\n"
"    ch    = ch,\n"
"    cs    = cs,\n"
"    zh    = sand.reshape(-1, 1),\n"
"    zs    = tuple(zs_soft),          # pass as tuple: (softpdftype, nl, limi, probdens)\n"
"    covmodel = covmodel,\n"
"    covparam = covparam,\n"
"    order    = order,\n"
"    nhmax    = nhmax,\n"
"    nsmax    = nsmax,\n"
"    dmax     = np.array([[dmax]]),\n"
")\n\n"
"zk_bme_mean = result[:, 0]\n"
"zk_bme_var  = result[:, 1]\n"
"print(f'BME estimated {np.sum(~np.isnan(zk_bme_mean))} / {len(ck)} nodes')\n"
"print(f'  Mean estimate : {np.nanmean(zk_bme_mean):.2f}%')\n"
"print(f'  Mean variance : {np.nanmean(zk_bme_var):.4f}')\n"
))

cells.append(nbf.v4.new_code_cell(
"def plot_map(ax, ck, zk, title, n_e, n_n, cmap='hot_r',\n"
"             ch_data=None, data_vals=None, cs_data=None,\n"
"             vmin=None, vmax=None, cbar_label=''):\n"
"    eu = np.unique(ck[:, 0])\n"
"    nu = np.unique(ck[:, 1])\n"
"    Z  = zk.reshape(n_n, n_e)\n"
"    vm = vmin if vmin is not None else np.nanpercentile(zk, 2)\n"
"    vx = vmax if vmax is not None else np.nanpercentile(zk, 98)\n"
"    im = ax.pcolormesh(eu, nu, Z, cmap=cmap, vmin=vm, vmax=vx, shading='nearest')\n"
"    plt.colorbar(im, ax=ax, label=cbar_label)\n"
"    if ch_data is not None and data_vals is not None:\n"
"        ax.scatter(ch_data[:, 0], ch_data[:, 1], c=data_vals, cmap=cmap,\n"
"                   vmin=vm, vmax=vx, edgecolors='k', lw=0.5, s=50,\n"
"                   marker='s', zorder=4, label='Hard')\n"
"    if cs_data is not None:\n"
"        ax.scatter(cs_data[:, 0], cs_data[:, 1],\n"
"                   facecolors='none', edgecolors='steelblue',\n"
"                   s=30, lw=0.5, zorder=3, label='Soft')\n"
"    ax.set_title(title)\n"
"    ax.set_aspect('equal')\n"
"    ax.set_xlabel('Easting (m)')\n"
"    ax.set_ylabel('Northing (m)')\n\n"
"vlo, vhi = 0.0, 60.0\n"
"fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
"plot_map(axes[0], ck, zk_bme_mean, 'BME mean - Sand (%)', n_e, n_n,\n"
"         ch_data=ch, data_vals=sand, cs_data=cs,\n"
"         vmin=vlo, vmax=vhi, cbar_label='Sand (%)')\n"
"plot_map(axes[1], ck, zk_bme_var,  'BME variance', n_e, n_n,\n"
"         cmap='Blues', cbar_label='Variance')\n"
"plt.suptitle('BME estimation with interval soft data', fontsize=12, y=1.01)\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 4. BME vs. Ordinary Kriging\n\n"
"Ordinary kriging ignores the interval soft data entirely (since it is not "
"a hard observation).  BME incorporates the soft data via its probabilistic "
"framework, generally reducing the estimation variance in regions covered by "
"the soft data.\n"
))

cells.append(nbf.v4.new_code_cell(
"if krig_available:\n"
"    fig, axes = plt.subplots(2, 2, figsize=(14, 11))\n"
"    vlo, vhi = 0.0, 60.0\n"
"    plot_map(axes[0, 0], ck, zk_ok_mean, 'OK mean', n_e, n_n,\n"
"             ch_data=ch, data_vals=sand,\n"
"             vmin=vlo, vmax=vhi, cbar_label='Sand (%)')\n"
"    plot_map(axes[0, 1], ck, zk_bme_mean, 'BME mean (+ interval soft)', n_e, n_n,\n"
"             ch_data=ch, data_vals=sand, cs_data=cs,\n"
"             vmin=vlo, vmax=vhi, cbar_label='Sand (%)')\n"
"    plot_map(axes[1, 0], ck, zk_ok_var,  'OK variance', n_e, n_n,\n"
"             cmap='Blues', cbar_label='Variance')\n"
"    plot_map(axes[1, 1], ck, zk_bme_var, 'BME variance', n_e, n_n,\n"
"             cmap='Blues', cbar_label='Variance')\n"
"    plt.suptitle('Ordinary Kriging vs. BME with interval soft data', fontsize=12, y=1.01)\n"
"    plt.tight_layout()\n"
"    plt.show()\n\n"
"    # Quantitative comparison\n"
"    delta_var = np.nanmean(zk_ok_var) - np.nanmean(zk_bme_var)\n"
"    pct_reduction = 100 * delta_var / np.nanmean(zk_ok_var)\n"
"    print(f'Mean OK variance  : {np.nanmean(zk_ok_var):.4f}')\n"
"    print(f'Mean BME variance : {np.nanmean(zk_bme_var):.4f}')\n"
"    print(f'Variance reduction: {pct_reduction:.1f}% (due to soft data)')\n"
"else:\n"
"    print('Kriging results not available. Run Tutorial 04 first to compare.')\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 5. Effect of soft data neighbourhood size\n\n"
"The `nsmax` parameter controls how many soft data points are used per estimation "
"node.  Using too few may miss relevant interval measurements; too many may "
"slow down computation.\n"
))

cells.append(nbf.v4.new_code_cell(
"nsmax_vals = [4, 8, 16]\n"
"fig, axes  = plt.subplots(1, 3, figsize=(17, 5))\n\n"
"for ax, ns in zip(axes, nsmax_vals):\n"
"    res = BMEPosteriorMoments(\n"
"        ck,\n"
"        ch=ch, cs=cs,\n"
"        zh=sand.reshape(-1, 1),\n"
"        zs=tuple(zs_soft),\n"
"        covmodel=covmodel,\n"
"        covparam=covparam,\n"
"        order=np.nan,\n"
"        nhmax=nhmax, nsmax=ns, dmax=np.array([[dmax]]),\n"
"    )\n"
"    plot_map(ax, ck, res[:, 0], f'BME mean  nsmax={ns}', n_e, n_n,\n"
"             ch_data=ch, data_vals=sand,\n"
"             vmin=vlo, vmax=vhi, cbar_label='Sand (%)')\n\n"
"plt.suptitle('Sensitivity to nsmax (soft data neighbourhood)', fontsize=12, y=1.01)\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_code_cell(
"# Save BME results for Tutorial 06\n"
"import pickle\n\n"
"bme05_results = {\n"
"    'zk_bme_mean': zk_bme_mean,\n"
"    'zk_bme_var':  zk_bme_var,\n"
"}\n"
"save_path = os.path.join(DATA_DIR, 'tutorial05_bme.pkl')\n"
"with open(save_path, 'wb') as f:\n"
"    pickle.dump(bme05_results, f)\n"
"print('Saved:', save_path)\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 6. Summary\n\n"
"| Step | stamps_v3 function | Notes |\n"
"|---|---|---|\n"
"| Encode intervals | `probaUniform(zlow, zup)` | Returns `(softpdftype, nl, limi, probdens)` |\n"
"| Soft data statistics | `proba2stat(...)` | Compute mean and variance of each soft PDF |\n"
"| BME estimation | `BMEPosteriorMoments(...)` | Bayesian update combining hard + soft data |\n\n"
"**Key insights:**\n"
"- Interval soft data carry less information than hard data but more than knowing nothing.\n"
"- BME reduces estimation variance compared to kriging wherever soft data exist.\n"
"- The variance reduction is larger when intervals are narrow and spatially dense.\n\n"
"**Next:** Tutorial 06 - BME with full probabilistic soft data (arbitrary PDFs).\n"
))

nb.cells = cells
import nbformat
with open("tutorials/05_bme_interval_soft_data.ipynb", "w") as f:
    nbformat.write(nb, f)
print("Written: tutorials/05_bme_interval_soft_data.ipynb")
