# -*- coding: utf-8 -*-
"""Generate 04_kriging_and_cokriging.ipynb"""
import nbformat as nbf

nb = nbf.v4.new_notebook()
nb.metadata['kernelspec'] = {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'}
nb.metadata['language_info'] = {'name': 'python', 'version': '3.9.0'}
cells = []

cells.append(nbf.v4.new_markdown_cell(
"# Tutorial 04 - Kriging, Cokriging & Kriging with Transformation\n\n"
"**Package:** stamps_v3  \n"
"**MATLAB equivalent:** `BMEHRLIBtutorial.m`  \n"
"**Dataset:** Falmagne soil dataset\n\n"
"---\n\n"
"## Learning objectives\n\n"
"1. Apply **ordinary kriging** of sand content on a 17 x 19 grid.\n"
"2. Apply **multivariate cokriging** jointly exploiting sand + silt + clay.\n"
"3. Apply **cokriging with transformation** (`cokrigingT`) using the Normal Score "
"   Transform (NST) fitted in Tutorial 03.\n"
"4. Compare the three estimation strategies side-by-side.\n\n"
"### Key stamps_v3 functions\n\n"
"| Function | Module | Purpose |\n"
"|---|---|---|\n"
"| `kriging` | `stamps.stest.kriging` | Univariate OK/SK |\n"
"| `cokriging` | `stamps.stest.kriging` | Multivariate LMC cokriging |\n"
"| `cokrigingT` | `stamps.stest.kriging` | LMC cokriging + NST back-transform |\n"
))

cells.append(nbf.v4.new_code_cell(
"import sys, os, pickle\n"
"import numpy as np\n"
"import matplotlib.pyplot as plt\n\n"
"REPO_ROOT = os.path.abspath(os.path.join(os.getcwd(), '..'))\n"
"if REPO_ROOT not in sys.path:\n"
"    sys.path.insert(0, REPO_ROOT)\n\n"
"from stamps.estimation.kriging import kriging, cokriging, cokrigingT\n\n"
"plt.rcParams.update({'figure.dpi': 110, 'font.size': 10})\n"
"DATA_DIR = os.path.join(os.getcwd(), 'data')\n\n"
"# --- Load dataset from Tutorial 01 ---\n"
"with open(os.path.join(DATA_DIR, 'tutorial01_data.pkl'), 'rb') as f:\n"
"    d1 = pickle.load(f)\n"
"ch   = d1['ch']\n"
"sand = d1['sand']\n"
"silt = d1['silt']\n"
"clay = d1['clay']\n"
"ck   = d1['ck']\n"
"n_e  = d1['n_e']\n"
"n_n  = d1['n_n']\n\n"
"# --- Load covariance / LMC parameters from Tutorial 03 ---\n"
"with open(os.path.join(DATA_DIR, 'tutorial03_cov.pkl'), 'rb') as f:\n"
"    cov = pickle.load(f)\n\n"
"sand_model  = cov['sand_covmodel']      # e.g. ['nuggetC', 'sphericalC']\n"
"sand_param  = cov['sand_covparam']      # [(c0,), (c1, a1)]\n"
"lmc_result  = cov['lmc_result']         # list of dicts from coregfit\n"
"z_sorted    = cov['sand_z_sorted']      # sorted original sand values\n"
"p_vals      = cov['sand_p_vals']        # corresponding CDF probabilities\n"
"nst_model   = cov['sand_nst_covmodel']  # e.g. ['nuggetC', 'sphericalC']\n"
"nst_param   = cov['sand_nst_covparam']  # parameters in NST space\n\n"
"print('Data:', ch.shape, '  Grid:', ck.shape)\n"
"print('Ordinary kriging model:', sand_model)\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 1. Ordinary kriging of sand content\n\n"
"Ordinary kriging (OK) minimises the estimation error variance subject to "
"the unbiasedness constraint $\\sum_\\alpha \\lambda_\\alpha = 1$.  "
"It relies only on the univariate covariance model of the target variable.\n"
))

cells.append(nbf.v4.new_code_cell(
"# Kriging neighbourhood parameters\n"
"nhmax = 25\n"
"dmax  = 10_000.0   # 10 km\n"
"order = 0          # ordinary kriging\n\n"
"print('Running ordinary kriging...')\n"
"zk_mean, zk_var = kriging(\n"
"    ck, ch, sand,\n"
"    sand_model, sand_param,\n"
"    nhmax, dmax, order\n"
")\n"
"print(f'  Estimated nodes : {np.sum(~np.isnan(zk_mean))} / {len(ck)}')\n"
"print(f'  Mean estimate   : {np.nanmean(zk_mean):.2f}%')\n"
"print(f'  Mean variance   : {np.nanmean(zk_var):.4f}')\n"
))

cells.append(nbf.v4.new_code_cell(
"# Helper: plot estimation map\n"
"def plot_map(ax, ck, zk, title, n_e, n_n, cmap='hot_r',\n"
"             ch_data=None, data_vals=None, vmin=None, vmax=None, cbar_label=''):\n"
"    eu = np.unique(ck[:, 0])\n"
"    nu = np.unique(ck[:, 1])\n"
"    Z  = zk.reshape(n_n, n_e)\n"
"    vm = vmin if vmin is not None else np.nanpercentile(zk, 2)\n"
"    vx = vmax if vmax is not None else np.nanpercentile(zk, 98)\n"
"    im = ax.pcolormesh(eu, nu, Z, cmap=cmap, vmin=vm, vmax=vx, shading='nearest')\n"
"    plt.colorbar(im, ax=ax, label=cbar_label)\n"
"    if ch_data is not None and data_vals is not None:\n"
"        ax.scatter(ch_data[:, 0], ch_data[:, 1], c=data_vals, cmap=cmap,\n"
"                   vmin=vm, vmax=vx, edgecolors='k', lw=0.5, s=45, zorder=3)\n"
"    ax.set_title(title)\n"
"    ax.set_aspect('equal')\n"
"    ax.set_xlabel('Easting (m)')\n"
"    ax.set_ylabel('Northing (m)')\n\n"
"vlo, vhi = 0.0, 60.0\n"
"fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
"plot_map(axes[0], ck, zk_mean, 'OK mean - Sand (%)', n_e, n_n,\n"
"         ch_data=ch, data_vals=sand, vmin=vlo, vmax=vhi, cbar_label='Sand (%)')\n"
"plot_map(axes[1], ck, zk_var,  'OK variance', n_e, n_n,\n"
"         cmap='Blues', cbar_label='Variance')\n"
"plt.suptitle('Ordinary Kriging - Sand content', fontsize=12, y=1.01)\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 2. Multivariate cokriging\n\n"
"Cokriging extends kriging to multiple co-regionalised variables.  "
"All three soil fractions (sand, silt, clay) are jointly exploited using the "
"**Linear Model of Coregionalization (LMC)** fitted in Tutorial 03.\n\n"
"The LMC cross-covariance between variable $i$ at lag $h$ is:\n\n"
"$$C_{ij}(h) = \\sum_k B_k[i,j]\\, g_k(h)$$\n\n"
"where $B_k$ are the sill matrices and $g_k$ are the basic spatial structures.\n\n"
"**stamps_v3 function:**\n"
"```python\n"
"zk_mean, zk_var = cokriging(\n"
"    ck, ck_var,    # estimation coords and variable indices\n"
"    ch, ch_var,    # data coords and variable indices\n"
"    zh,            # data values\n"
"    lmc_models,    # list of dicts from coregfit\n"
"    nhmax, dmax, order\n"
")\n"
"```\n"
))

cells.append(nbf.v4.new_code_cell(
"n_pts = len(ch)\n\n"
"# Stack all three variables\n"
"ch_all  = np.vstack([ch, ch, ch])                    # (3n, 2)\n"
"zh_all  = np.concatenate([sand, silt, clay])          # (3n,)\n"
"var_all = np.concatenate([np.zeros(n_pts, dtype=int),  # 0 = sand\n"
"                           np.ones( n_pts, dtype=int),  # 1 = silt\n"
"                           2 * np.ones(n_pts, dtype=int)])  # 2 = clay\n\n"
"# All estimation locations target variable 0 (sand)\n"
"ck_var = np.zeros(len(ck), dtype=int)\n\n"
"print('LMC structures:')\n"
"for s in lmc_result:\n"
"    print(f'  {s[\"model\"]}  sill matrix =\\n{np.round(s[\"sill_matrix\"], 2)}')\n\n"
"print('\\nRunning cokriging...')\n"
"zk_cok_mean, zk_cok_var = cokriging(\n"
"    ck, ck_var,\n"
"    ch_all, var_all,\n"
"    zh_all,\n"
"    lmc_result,\n"
"    nhmax=15, dmax=10_000.0, order=0\n"
")\n"
"print(f'  Estimated nodes : {np.sum(~np.isnan(zk_cok_mean))} / {len(ck)}')\n"
"print(f'  Mean variance   : {np.nanmean(zk_cok_var):.4f}')\n"
))

cells.append(nbf.v4.new_code_cell(
"fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
"plot_map(axes[0], ck, zk_cok_mean, 'Cokriging mean - Sand (%)', n_e, n_n,\n"
"         ch_data=ch, data_vals=sand, vmin=vlo, vmax=vhi, cbar_label='Sand (%)')\n"
"plot_map(axes[1], ck, zk_cok_var,  'Cokriging variance', n_e, n_n,\n"
"         cmap='Blues', cbar_label='Variance')\n"
"plt.suptitle('Multivariate Cokriging - Sand content', fontsize=12, y=1.01)\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 3. Cokriging with Normal Score Transformation (`cokrigingT`)\n\n"
"`cokrigingT` implements the full NST workflow automatically:\n\n"
"1. **Forward transform**: map each observation to Gaussian scores using the reference CDF.\n"
"2. **Cokriging**: estimate in the Gaussian-score space.\n"
"3. **Back-transformation**: convert the Gaussian posterior mean/variance back "
"   to the original scale via numerical integration of the back-transformed density.\n\n"
"This is the recommended workflow when the marginal distribution is strongly non-Gaussian.\n\n"
"```python\n"
"zk_mean, zk_var = cokrigingT(\n"
"    ck, ck_var,\n"
"    ch, ch_var,\n"
"    yh,            # original (non-Gaussian) data\n"
"    lmc_models,    # LMC in NST space\n"
"    nhmax, dmax,\n"
"    yfiles,        # list of reference y-values per variable\n"
"    cdfy_files,    # list of reference CDF values per variable\n"
"    order\n"
")\n"
"```\n"
))

cells.append(nbf.v4.new_code_cell(
"# For univariate NST kriging: use the single-variable LMC (nst_result)\n"
"# Build a 1-variable LMC from the univariate fitted NST parameters\n"
"from stamps.models.covmodel import nuggetC, sphericalC\n\n"
"def build_lmc_from_univariate(model_names, model_params):\n"
"    \"\"\"Convert univariate model params to LMC format (1x1 sill matrices).\"\"\"\n"
"    lmc = []\n"
"    for name, param in zip(model_names, model_params):\n"
"        entry = {'model': name, 'sill_matrix': np.array([[param[0]]])}\n"
"        if len(param) > 1:\n"
"            entry['range_param'] = param[1]\n"
"        lmc.append(entry)\n"
"    return lmc\n\n"
"nst_lmc = build_lmc_from_univariate(nst_model, nst_param)\n\n"
"print('NST LMC structures:')\n"
"for s in nst_lmc:\n"
"    print(f'  {s[\"model\"]}  sill={s[\"sill_matrix\"][0,0]:.3f}', end='')\n"
"    if 'range_param' in s:\n"
"        print(f'  range={s[\"range_param\"]:.1f} m')\n"
"    else:\n"
"        print()\n\n"
"# All data are sand (variable 0), all estimation locations target sand (variable 0)\n"
"var_sand  = np.zeros(n_pts,      dtype=int)\n"
"ck_var_0  = np.zeros(len(ck),   dtype=int)\n\n"
"# Reference CDF lists (one per variable; here only one variable)\n"
"yfiles_list    = [z_sorted]   # reference y-values for variable 0 (sand)\n"
"cdfy_files_list = [p_vals]    # reference CDF for variable 0 (sand)\n\n"
"print('\\nRunning cokrigingT (NST)...')\n"
"zk_nst_mean, zk_nst_var = cokrigingT(\n"
"    ck, ck_var_0,\n"
"    ch, var_sand,\n"
"    sand,          # original sand data (will be transformed internally)\n"
"    nst_lmc,\n"
"    nhmax=25, dmax=10_000.0,\n"
"    yfiles=yfiles_list,\n"
"    cdfy_files=cdfy_files_list,\n"
"    order=0\n"
")\n"
"print(f'  Estimated nodes : {np.sum(~np.isnan(zk_nst_mean))} / {len(ck)}')\n"
"print(f'  Mean estimate   : {np.nanmean(zk_nst_mean):.2f}%')\n"
))

cells.append(nbf.v4.new_code_cell(
"fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
"plot_map(axes[0], ck, zk_nst_mean, 'KrigingT mean - Sand (%)', n_e, n_n,\n"
"         ch_data=ch, data_vals=sand, vmin=vlo, vmax=vhi, cbar_label='Sand (%)')\n"
"plot_map(axes[1], ck, zk_nst_var,  'KrigingT variance', n_e, n_n,\n"
"         cmap='Blues', cbar_label='Variance')\n"
"plt.suptitle('Kriging with NST Back-Transformation', fontsize=12, y=1.01)\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_markdown_cell("## 4. Three-way comparison\n\n"
"Compare the mean estimate and estimation variance of the three methods.\n"))

cells.append(nbf.v4.new_code_cell(
"fig, axes = plt.subplots(2, 3, figsize=(18, 10))\n\n"
"titles_mean = ['OK mean', 'Cokriging mean', 'KrigingT mean']\n"
"titles_var  = ['OK variance', 'Cokriging variance', 'KrigingT variance']\n"
"means = [zk_mean,     zk_cok_mean,  zk_nst_mean]\n"
"vars_ = [zk_var,      zk_cok_var,   zk_nst_var]\n\n"
"for i, (mu, va, tm, tv) in enumerate(zip(means, vars_, titles_mean, titles_var)):\n"
"    plot_map(axes[0, i], ck, mu, tm, n_e, n_n,\n"
"             ch_data=ch, data_vals=sand, vmin=vlo, vmax=vhi, cbar_label='Sand (%)')\n"
"    plot_map(axes[1, i], ck, va, tv, n_e, n_n,\n"
"             cmap='Blues', cbar_label='Variance')\n\n"
"plt.suptitle('Kriging methods comparison - Sand content', fontsize=13, y=1.01)\n"
"plt.tight_layout()\n"
"plt.show()\n\n"
"print('Mean estimation variance comparison:')\n"
"print(f'  OK          : {np.nanmean(zk_var):.4f}')\n"
"print(f'  Cokriging   : {np.nanmean(zk_cok_var):.4f}')\n"
"print(f'  KrigingT    : {np.nanmean(zk_nst_var):.4f}')\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 5. Neighbourhood sensitivity\n\n"
"Kriging results depend on the neighbourhood parameters `nhmax` and `dmax`.  "
"A larger search radius includes more data but may incorporate points with "
"very low spatial correlation.\n"
))

cells.append(nbf.v4.new_code_cell(
"dmax_vals = [5_000, 10_000, 20_000]\n"
"fig, axes = plt.subplots(1, 3, figsize=(17, 5))\n\n"
"for ax, dv in zip(axes, dmax_vals):\n"
"    zk_m, zk_v = kriging(\n"
"        ck, ch, sand,\n"
"        sand_model, sand_param,\n"
"        nhmax=25, dmax=float(dv), order=0\n"
"    )\n"
"    plot_map(ax, ck, zk_m, f'OK  dmax={dv//1000} km', n_e, n_n,\n"
"             ch_data=ch, data_vals=sand,\n"
"             vmin=vlo, vmax=vhi, cbar_label='Sand (%)')\n\n"
"plt.suptitle('Effect of search radius on kriging estimate', fontsize=12, y=1.01)\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

cells.append(nbf.v4.new_code_cell(
"# Save results for Tutorial 05\n"
"import pickle\n\n"
"krig_results = {\n"
"    'zk_ok_mean':  zk_mean,\n"
"    'zk_ok_var':   zk_var,\n"
"    'zk_cok_mean': zk_cok_mean,\n"
"    'zk_cok_var':  zk_cok_var,\n"
"    'zk_nst_mean': zk_nst_mean,\n"
"    'zk_nst_var':  zk_nst_var,\n"
"}\n"
"save_path = os.path.join(DATA_DIR, 'tutorial04_krig.pkl')\n"
"with open(save_path, 'wb') as f:\n"
"    pickle.dump(krig_results, f)\n"
"print('Saved:', save_path)\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 6. Summary\n\n"
"| Method | Variables used | Notes |\n"
"|---|---|---|\n"
"| Ordinary Kriging | Sand only | Baseline, assumes Gaussian distribution |\n"
"| Cokriging | Sand + Silt + Clay | Exploits cross-correlations (LMC) |\n"
"| KrigingT | Sand (via NST) | Handles non-Gaussian marginals correctly |\n\n"
"**Key insights:**\n"
"- Cokriging reduces estimation variance when auxiliary variables are correlated with the target.\n"
"- `cokrigingT` is preferred when the marginal distribution is significantly non-Gaussian.\n"
"- For weakly correlated auxiliary variables, cokriging converges to ordinary kriging.\n\n"
"**Next:** Tutorial 05 - BME with interval (soft) data.\n"
))

nb.cells = cells
import nbformat
with open("tutorials/04_kriging_and_cokriging.ipynb", "w") as f:
    nbformat.write(nb, f)
print("Written: tutorials/04_kriging_and_cokriging.ipynb")
